import json
import os

phonics_words = []

# List of 400 words grouped in 8 categories of 50 words each
raw_data = [
    # CATEGORY 1: Short Vowels (50 words)
    {
        "category": "Short Vowels",
        "words": [
            ("cat", "/kæt/", "noun", "🐱", "a small furry animal", "ឆ្មា", "The cat slept on the mat.", "ឆ្មាដេកនៅលើកម្រាលព្រំ។"),
            ("bat", "/bæt/", "noun", "🦇", "a flying mammal active at night", "ប្រចៀវ", "A bat flies in the dark.", "ប្រចៀវហើរក្នុងងងឹត។"),
            ("hat", "/hæt/", "noun", "🎩", "a covering for the head", "មួក", "He wore a black hat.", "គាត់ពាក់មួកពណ៌ខ្មៅ។"),
            ("fat", "/fæt/", "adjective", "🐖", "having a large amount of excess flesh", "ធាត់", "The fat pig was eating.", "ជ្រូកធាត់កំពុងស៊ីចំណី។"),
            ("rat", "/ræt/", "noun", "🐀", "a rodent resembling a large mouse", "កណ្តុរ", "The rat ran under the table.", "កណ្តុរកំពុងរត់ក្រោមតុ។"),
            ("mat", "/mæt/", "noun", "🔲", "a piece of fabric placed on a floor", "កម្រាល", "Wipe your feet on the mat.", "ជូតជើងរបស់អ្នកនៅលើកម្រាល។"),
            ("map", "/mæp/", "noun", "🗺️", "a visual representation of an area", "ផែនទី", "We look at the map for directions.", "យើងមើលផែនទីដើម្បីរកផ្លូវ។"),
            ("cap", "/kæp/", "noun", "🧢", "a close-fitting head covering with a brim", "មួកចំបើង", "He has a blue cap.", "គាត់មានមួកចំបើងពណ៌ខៀវ។"),
            ("tap", "/tæp/", "noun", "🚰", "a device for controlling flow of liquid", "ក្បាលរ៉ូប៊ីណេ", "Water comes out of the tap.", "ទឹកចេញពីក្បាលរ៉ូប៊ីណេ។"),
            ("nap", "/næp/", "noun", "💤", "a short sleep during the day", "ការគេងមួយភាំង", "The baby takes a nap in the afternoon.", "ទារកគេងមួយភាំងនៅពេលរសៀល។"),
            ("bag", "/bæɡ/", "noun", "👜", "a container for carrying things", "កាបូប", "Put the book in your bag.", "ដាក់សៀវភៅក្នុងកាបូបរបស់អ្នក។"),
            ("tag", "/tæɡ/", "noun", "🏷️", "a label attached to something", "ស្លាក", "Check the price tag on the shirt.", "ពិនិត្យមើលស្លាកតម្លៃនៅលើអាវ។"),
            ("rag", "/ræɡ/", "noun", "🧹", "a piece of old cloth used for cleaning", "កំណាត់ចាស់", "Use a wet rag to wipe the dust.", "ប្រើកំណាត់ចាស់សើមដើម្បីជូតធូលី។"),
            ("van", "/væn/", "noun", "🚐", "a medium-sized motor vehicle", "ឡានវ៉ែន", "The family traveled in a van.", "គ្រួសារបានធ្វើដំណើរតាមឡានវ៉ែន។"),
            ("pan", "/pæn/", "noun", "🍳", "a metal container used for cooking", "ខ្ទះ", "Fry the egg in the pan.", "ចៀនពងទានៅក្នុងខ្ទះ។"),
            ("can", "/kæn/", "noun", "🥫", "a cylindrical metal container", "កំប៉ុង", "He drank a can of soda.", "គាត់ផឹកសូដាមួយកំប៉ុង។"),
            ("man", "/mæn/", "noun", "👨", "an adult human male", "បុរស", "The man is walking down the street.", "បុរសនោះកំពុងដើរតាមផ្លូវ។"),
            ("fan", "/fæn/", "noun", "🪭", "a device used to create a current of air", "កង្ហារ", "Turn on the fan, it is hot.", "បើកកង្ហារទៅ វាពិតជាក្តៅណាស់។"),
            ("red", "/red/", "adjective", "🔴", "the color of blood or a ruby", "ពណ៌ក្រហម", "She drew a red flower.", "នាងគូរផ្កាពណ៌ក្រហមមួយ។"),
            ("bed", "/bed/", "noun", "🛏️", "a piece of furniture for sleeping on", "គ្រែ", "Go to bed early tonight.", "ចូលគេងឱ្យបានលឿនយប់នេះ។"),
            ("net", "/net/", "noun", "🕸️", "a mesh of cords used to catch things", "សំណាញ់", "He caught a butterfly with a net.", "គាត់ចាប់មេអំបៅដោយប្រើសំណាញ់។"),
            ("pet", "/pet/", "noun", "🐶", "a domestic animal kept for companionship", "សត្វចិញ្ចឹម", "A dog is a friendly pet.", "ឆ្កែគឺជាសត្វចិញ្ចឹមដែលគួរឱ្យស្រឡាញ់។"),
            ("wet", "/wet/", "adjective", "💧", "covered or saturated with liquid", "សើម", "His clothes got wet in the rain.", "ខោអាវរបស់គាត់សើមអស់ហើយដោយសារទឹកភ្លៀង។"),
            ("hen", "/hen/", "noun", "🐔", "a female chicken", "មេមាន់", "The hen laid an egg.", "មេមាន់ពងបានមួយ។"),
            ("pen", "/pen/", "noun", "🖊️", "an instrument for writing with ink", "ប៊ិច", "Write your name with a blue pen.", "សរសេរឈ្មោះរបស់អ្នកដោយប៊ិចពណ៌ខៀវ។"),
            ("ten", "/ten/", "number", "🔟", "equivalent to the product of five and two", "ដប់", "I have ten fingers.", "ខ្ញុំមានម្រាមដៃដប់។"),
            ("leg", "/leɡ/", "noun", "🦵", "a limb used for walking or standing", "ជើង", "He hurt his leg playing football.", "គាត់ឈឺជើងពេលលេងបាល់ទាត់។"),
            ("peg", "/peɡ/", "noun", "📌", "a wooden or plastic pin for hanging clothes", "កូសខោអាវ", "Hang the clothes with a peg.", "ព្យួរខោអាវដោយប្រើកូសខោអាវ។"),
            ("jet", "/dʒet/", "noun", "✈️", "a rapid stream of liquid or gas; an airplane", "យន្តហោះចម្បាំង", "The jet flew high in the sky.", "យន្តហោះចម្បាំងហើរខ្ពស់លើមេឃ។"),
            ("pin", "/pɪn/", "noun", "📌", "a thin piece of metal used for fastening", "ម្ជុលខ្ទាស់", "She used a pin to hold the cloth.", "នាងប្រើម្ជុលខ្ទាស់ដើម្បីទប់កំណាត់។"),
            ("tin", "/tɪn/", "noun", "🥫", "a type of metal; a metal can for food", "កំប៉ុងដែក", "The fish is in a tin.", "ត្រីនៅក្នុងកំប៉ុងដែក។"),
            ("win", "/wɪn/", "verb", "🏆", "to achieve victory in a game or contest", "ឈ្នះ", "We want to win the game.", "ពួកយើងចង់ឈ្នះការប្រកួតនេះ។"),
            ("fin", "/fɪn/", "noun", "🦈", "a winglike projection on a fish's body", "ព្រុយត្រី", "The shark has a sharp fin.", "ត្រីឆ្លាមមានព្រុយស្រួច។"),
            ("bin", "/bɪn/", "noun", "🗑️", "a container for waste or trash", "ធុងសំរាម", "Throw the paper in the bin.", "បោះក្រដាសចូលក្នុងធុងសំរាម។"),
            ("hit", "/hɪt/", "verb", "🏏", "to strike or bring into contact with force", "វាយ", "He can hit the ball far.", "គាត់អាចវាយបាល់បានឆ្ងាយ។"),
            ("sit", "/sɪt/", "verb", "🪑", "to rest one's weight on the buttocks", "អង្គុយ", "Sit on the chair, please.", "សូមអង្គុយលើកៅអី។"),
            ("fit", "/fɪt/", "adjective", "💪", "in good health or athletic shape", "សមសួន/រឹងមាំ", "He runs to stay healthy and fit.", "គាត់រត់ដើម្បីរក្សាសុខភាពនិងរាងកាយសមសួន។"),
            ("pit", "/pɪt/", "noun", "🕳️", "a large deep hole in the ground", "រណ្តៅ", "There is a deep pit in the garden.", "មានរណ្តៅដ៏ជ្រៅមួយនៅក្នុងសួនច្បារ។"),
            ("lip", "/lɪp/", "noun", "👄", "either of the two fleshy parts of the mouth", "បបូរមាត់", "He has a dry lip.", "គាត់មានបបូរមាត់ស្ងួត។"),
            ("zip", "/zɪp/", "noun", "🤐", "a device used to open and close bags or clothes", "ខ្សែរ៉ូត", "Zip up your jacket.", "បិទខ្សែរ៉ូតអាវធំរបស់អ្នក។"),
            ("dog", "/dɒɡ/", "noun", "🐶", "a common domesticated carnivorous mammal", "ឆ្កែ", "The dog barks at the cat.", "ឆ្កែព្រុសដាក់ឆ្មា។"),
            ("log", "/lɒɡ/", "noun", "🪵", "a part of the trunk of a cut tree", "ដុំឈើ", "We burned a log in the fire.", "ពួកយើងដុតដុំឈើនៅក្នុងភ្លើង។"),
            ("hop", "/hɒp/", "verb", "🐰", "to move by jumping on one foot", "លោតញាប់ៗ", "The rabbits hop in the grass.", "ទន្សាយលោតញាប់ៗនៅលើវាលស្មៅ។"),
            ("mop", "/mɒp/", "noun", "🧹", "a tool for washing or cleaning floors", "ឈើជូតឥដ្ឋ", "Use a mop to clean the water.", "ប្រើឈើជូតឥដ្ឋដើម្បីសម្អាតទឹក។"),
            ("top", "/tɒp/", "noun", "🔝", "the highest point or part of something", "ផ្នែកខាងលើ", "He sat at the top of the hill.", "គាត់បានអង្គុយនៅលើកំពូលភ្នំ។"),
            ("bug", "/bʌɡ/", "noun", "🪲", "a small insect", "សត្វល្អិត", "A small bug crawled on the leaf.", "សត្វល្អិតតូចមួយកំពុងវារនៅលើស្លឹកឈើ។"),
            ("rug", "/rʌɡ/", "noun", "🎴", "a floor covering similar to a carpet", "កម្រាលកម្រាល", "A colorful rug is on the floor.", "កម្រាលដ៏មានពណ៌ឆើតឆាយនៅលើឥដ្ឋ។"),
            ("hug", "/hʌɡ/", "verb", "🫂", "to squeeze tightly in one's arms in affection", "ឱប", "Give your mom a warm hug.", "ផ្តល់ការឱបដ៏កក់ក្តៅដល់ម្តាយរបស់អ្នក។"),
            ("mug", "/mʌɡ/", "noun", "🍺", "a large cup with a handle used for hot drinks", "ពែងមានដៃ", "I drank hot milk from a mug.", "ខ្ញុំបានផឹកទឹកដោះគោក្តៅពីពែងមានដៃ។"),
            ("cup", "/kʌp/", "noun", "☕", "a small container used for drinking liquids", "ពែង", "She drank tea from a cup.", "នាងផឹកតែពីពែង។")
        ]
    },
    # CATEGORY 2: Long Vowels (50 words)
    {
        "category": "Long Vowels",
        "words": [
            ("cake", "/keɪk/", "noun", "🍰", "a sweet baked dessert", "នំខេក", "She baked a sweet cake.", "នាងបានដុតនំខេកដ៏ផ្អែមមួយ។"),
            ("lake", "/leɪk/", "noun", "🏞️", "a large body of water surrounded by land", "បឹង", "We swam in the cool lake.", "ពួកយើងបានហែលទឹកនៅក្នុងបឹងដ៏ត្រជាក់។"),
            ("gate", "/ɡeɪt/", "noun", "🚧", "a barrier like a door in a fence", "របងទ្វារ", "Close the gate behind you.", "បិទទ្វាររបងនៅពីក្រោយអ្នក។"),
            ("name", "/neɪm/", "noun", "📛", "a word by which a person or thing is known", "ឈ្មោះ", "My name is John.", "ឈ្មោះរបស់ខ្ញុំគឺចន។"),
            ("tape", "/teɪp/", "noun", "📼", "adhesive strip used to stick things together", "ស្កុត", "Use tape to fix the box.", "ប្រើស្កុតដើម្បីជួសជុលប្រអប់។"),
            ("face", "/feɪs/", "noun", "👧", "the front part of the head", "មុខ", "She had a happy smile on her face.", "នាងមានស្នាមញញឹមដ៏រីករាយនៅលើផ្ទៃមុខ។"),
            ("safe", "/seɪf/", "adjective", "🛡️", "protected from danger or harm", "សុវត្ថិភាព", "It is safe to cross the street now.", "វាមានសុវត្ថិភាពក្នុងការឆ្លងផ្លូវឥឡូវនេះ។"),
            ("grape", "/ɡreɪp/", "noun", "🍇", "a small green or purple berry growing in clusters", "ផ្លែទំពាំងបាយជូរ", "I like to eat purple grape.", "ខ្ញុំចូលចិត្តញ៉ាំផ្លែទំពាំងបាយជូរពណ៌ស្វាយ។"),
            ("game", "/ɡeɪm/", "noun", "🎮", "an activity played for entertainment or sport", "ល្បែង/ហ្គេម", "We played a fun board game.", "ពួកយើងបានលេងហ្គេមក្តារដ៏សប្បាយមួយ។"),
            ("plane", "/pleɪn/", "noun", "✈️", "an airplane that flies in the air", "យន្តហោះ", "The plane took off into the clouds.", "យន្តហោះបានហោះឡើងទៅលើពពក។"),
            ("bee", "/biː/", "noun", "🐝", "an insect that makes honey", "សត្វឃ្មុំ", "The bee buzzed around the flower.", "សត្វឃ្មុំហើរលាន់ឮជុំវិញផ្កា។"),
            ("tree", "/triː/", "noun", "🌳", "a tall woody plant with branches and leaves", "ដើមឈើ", "Birds built a nest in the tree.", "បក្សីបានធ្វើសំបុកនៅលើដើមឈើ។"),
            ("leaf", "/liːf/", "noun", "🍃", "a green flattened structure of a plant", "ស្លឹកឈើ", "A single green leaf fell to the ground.", "ស្លឹកឈើពណ៌បៃតងមួយបានជ្រុះមកដី។"),
            ("key", "/kiː/", "noun", "🔑", "a metal tool used to open locks", "សោ", "He lost the key to his room.", "គាត់បានបាត់សោចាក់បន្ទប់របស់គាត់។"),
            ("green", "/ɡriːn/", "adjective", "🟢", "the color of grass and emeralds", "ពណ៌បៃតង", "The grass is soft and green.", "ស្មៅមានសភាពទន់និងមានពណ៌បៃតង។"),
            ("see", "/siː/", "verb", "👀", "to perceive with the eyes", "ឃើញ", "I can see the mountains far away.", "ខ្ញុំអាចមើលឃើញភ្នំនៅឆ្ងាយ។"),
            ("feet", "/fiːt/", "noun", "🦶", "plural form of foot; used for walking", "ជើង (ច្រើន)", "Wash your feet before bed.", "លាងជើងរបស់អ្នកមុនពេលគេង។"),
            ("seat", "/siːt/", "noun", "🪑", "a place or thing to sit on", "កន្លែងអង្គុយ", "Please find a comfortable seat.", "សូមរកកន្លែងអង្គុយដែលស្រួល។"),
            ("meat", "/miːt/", "noun", "🥩", "the flesh of an animal used as food", "សាច់", "He doesn't eat red meat.", "គាត់មិនញ៉ាំសាច់ពណ៌ក្រហមទេ។"),
            ("eat", "/iːt/", "verb", "🍽️", "to consume food into the body", "ញ៉ាំ", "We eat lunch together at noon.", "ពួកយើងញ៉ាំអាហារថ្ងៃត្រង់ជាមួយគ្នានៅថ្ងៃត្រង់។"),
            ("bite", "/baɪt/", "verb", "🦷", "to cut with teeth", "ខាំ", "Don't bite your fingernails.", "កុំខាំក្រចកដៃរបស់អ្នក។"),
            ("kite", "/kaɪt/", "noun", "🪁", "a light toy flown in the wind on a string", "ខ្លែង", "The wind is perfect to fly a kite.", "ខ្យល់ពិតជាល្អណាស់សម្រាប់បង្ហោះខ្លែង។"),
            ("write", "/raɪt/", "verb", "📝", "to mark letters or words on paper", "សរសេរ", "Write your homework in the notebook.", "សរសេរកិច្ចការផ្ទះរបស់អ្នកនៅក្នុងសៀវភៅសរសេរ។"),
            ("time", "/taɪm/", "noun", "⏰", "the period of duration measured in hours/minutes", "ពេលវេលា", "What time does the lesson start?", "តើមេរៀនចាប់ផ្តើមនៅម៉ោងប៉ុន្មាន?"),
            ("bike", "/baɪk/", "noun", "🚲", "a bicycle with two wheels", "កង់", "He rides a bike to school.", "គាត់ជិះកង់ទៅសាលារៀន។"),
            ("lime", "/laɪm/", "noun", "🍋", "a sour green citrus fruit", "ក្រូចឆ្មារបៃតង", "Squeeze some lime juice on the fish.", "ច្របាច់ទឹកក្រូចឆ្មារបៃតងបន្តិចនៅលើត្រី។"),
            ("fire", "/faɪər/", "noun", "🔥", "combustion that produces heat and light", "ភ្លើង", "Keep away from the hot fire.", "នៅឱ្យឆ្ងាយពីភ្លើងក្តៅ។"),
            ("five", "/faɪv/", "number", "5️⃣", "equivalent to the sum of two and three", "ប្រាំ", "He has five blue pens.", "គាត់មានប៊ិចពណ៌ខៀវប្រាំដើម។"),
            ("pine", "/paɪn/", "noun", "🌲", "an evergreen coniferous tree with needles", "ដើមស្រល់", "We walked through the pine forest.", "ពួកយើងបានដើរកាត់ព្រៃស្រល់។"),
            ("fine", "/faɪn/", "adjective", "☀️", "of high quality; in good health or weather", "ល្អ/សុខសប្បាយ", "The weather is sunny and fine.", "អាកាសធាតុមានពន្លឺថ្ងៃនិងល្អណាស់។"),
            ("rope", "/roʊp/", "noun", "🪢", "thick strong cord made of twisted strands", "ខ្សែពួរ", "Tie the boat to the dock with a rope.", "ចងទូកទៅនឹងផែដោយប្រើខ្សែពួរ។"),
            ("home", "/hoʊm/", "noun", "🏠", "the place where one lives permanent", "ផ្ទះ", "We feel safe and happy at home.", "ពួកយើងមានអារម្មណ៍សុវត្ថិភាពនិងសប្បាយរីករាយនៅផ្ទះ។"),
            ("bone", "/boʊn/", "noun", "🦴", "hard structural part of a skeleton", "ឆ្អឹង", "The dog chewed on a hard bone.", "ឆ្កែកំពុងខាំឆ្អឹងដ៏រឹងមួយ។"),
            ("coat", "/koʊt/", "noun", "🧥", "an outer garment with sleeves worn for warmth", "អាវធំ", "Put on your warm coat, it is cold.", "ពាក់អាវធំដ៏កក់ក្តៅរបស់អ្នកទៅ វាពិតជាត្រជាក់ណាស់។"),
            ("boat", "/boʊt/", "noun", "⛵", "a small vessel for traveling on water", "ទូក", "We sailed a wooden boat on the lake.", "ពួកយើងបានជិះទូកឈើនៅលើបឹង។"),
            ("soap", "/soʊp/", "noun", "🧼", "a substance used for washing and cleaning", "សាប៊ូ", "Wash your hands with clean soap.", "លាងដៃរបស់អ្នកជាមួយសាប៊ូស្អាត។"),
            ("road", "/roʊd/", "noun", "🛣️", "a wide way for vehicles and people", "ផ្លូវ", "Drive safely on the busy road.", "បើកបរដោយសុវត្ថិភាពនៅលើផ្លូវដ៏មមាញឹក។"),
            ("goat", "/ɡoʊt/", "noun", "🐐", "a hardy domesticated mammal with horns", "ពពែ", "The white goat jumped over the rock.", "ពពែពណ៌សបានលោតរំលងដុំថ្ម។"),
            ("nose", "/noʊz/", "noun", "👃", "the part of the face used for smelling and breathing", "ច្រមុះ", "He blew his nose into a tissue.", "គាត់បានញើសច្រមុះចូលក្នុងក្រដាសជូតមាត់។"),
            ("rose", "/roʊz/", "noun", "🌹", "a sweet-smelling flower with thorny stems", "ផ្កាឡាប", "She picked a beautiful red rose.", "នាងបានបេះផ្កាឡាបពណ៌ក្រហមដ៏ស្រស់ស្អាតមួយ។"),
            ("blue", "/bluː/", "adjective", "🔵", "the color of the clear sky", "ពណ៌ខៀវ", "The sky is clear and blue today.", "មេឃស្រឡះនិងមានពណ៌ខៀវនៅថ្ងៃនេះ។"),
            ("flute", "/fluːt/", "noun", "🪈", "a high-pitched woodwind instrument", "ខ្លុយ", "He learned to play a wooden flute.", "គាត់បានរៀនផ្លុំខ្លុយឈើ។"),
            ("glue", "/ɡluː/", "noun", "🧪", "sticky substance used to join things together", "កាវ", "Use glue to stick the paper together.", "ប្រើកាវដើម្បីបិទក្រដាសចូលគ្នា។"),
            ("cute", "/kjuːt/", "adjective", "🐱", "attractive in a pretty or endearing way", "គួរឱ្យស្រឡាញ់", "Look at that cute little puppy.", "មើលកូនឆ្កែតូចគួរឱ្យស្រឡាញ់នោះមើល។"),
            ("tube", "/tuːb/", "noun", "🧪", "a hollow cylinder for liquids or gas", "បំពង់", "He squeezed a tube of toothpaste.", "គាត់បានច្របាច់បំពង់ថ្នាំដុសធ្មេញ។"),
            ("mule", "/mjuːl/", "noun", "🫏", "the offspring of a donkey and a horse", "លា", "The heavy pack was carried by a mule.", "កញ្ចប់ដ៏ធ្ងន់ត្រូវបានដឹកដោយលា។"),
            ("juice", "/dʒuːs/", "noun", "🍹", "liquid extracted from fruit or vegetables", "ទឹកផ្លែឈើ", "I want to drink fresh orange juice.", "ខ្ញុំចង់ផឹកទឹកក្រូចស្រស់។"),
            ("fruit", "/fruːt/", "noun", "🍎", "sweet fleshy product of a tree containing seeds", "ផ្លែឈើ", "Eat fresh fruit for vitamins.", "ញ៉ាំផ្លែឈើស្រស់ដើម្បីទទួលបានវីតាមីន។"),
            ("rain", "/reɪn/", "noun", "🌧️", "water falling in drops from vapor in the sky", "ទឹកភ្លៀង", "Heavy rain fell in the afternoon.", "ភ្លៀងធ្លាក់ខ្លាំងនៅពេលរសៀល។"),
            ("train", "/treɪn/", "noun", "🚆", "connected railway carriages pulled by an engine", "រថភ្លើង", "We traveled across the country by train.", "ពួកយើងបានធ្វើដំណើរឆ្លងកាត់ប្រទេសតាមរថភ្លើង។")
        ]
    },
    # CATEGORY 3: Consonant Digraphs (50 words)
    {
        "category": "Consonant Digraphs",
        "words": [
            ("chair", "/tʃeər/", "noun", "🪑", "a separate seat for one person, with a back", "កៅអី", "Sit on the wooden chair.", "អង្គុយលើកៅអីឈើ។"),
            ("rich", "/rɪtʃ/", "adjective", "💰", "having a great deal of money or assets", "មាន/ធូរធារ", "The rich merchant donated to the school.", "ពាណិជ្ជករដ៏មានបានម្នាក់បានបរិច្ចាគដល់សាលារៀន។"),
            ("much", "/mʌtʃ/", "adjective", "📈", "a great amount or quantity", "ច្រើន", "Thank you very much for your help.", "សូមអរគុណច្រើនសម្រាប់ការជួយរបស់អ្នក។"),
            ("chip", "/tʃɪp/", "noun", "🍟", "a thin slice of food, typically potato", "ដំឡូងបារាំងបំពង", "He ate a salty potato chip.", "គាត់បានញ៉ាំដំឡូងបារាំងបំពងដ៏ប្រៃ។"),
            ("chin", "/tʃɪn/", "noun", "🧔", "the protruding part of the face below the mouth", "ចង្កា", "He scratched his chin thoughtfully.", "គាត់បានអូសចង្កាដោយការគិត។"),
            ("chop", "/tʃɒp/", "verb", "🪓", "to cut into pieces with repeated blows", "កាប់/ចិញ្រ្ចាំ", "Use an axe to chop the firewood.", "ប្រើពូថៅដើម្បីកាប់អុស។"),
            ("chat", "/tʃæt/", "verb", "💬", "to talk in a friendly, informal way", "ជជែកកំសាន្ត", "They sat in the garden to chat.", "ពួកគេបានអង្គុយនៅក្នុងសួនច្បារដើម្បីជជែកកំសាន្ត។"),
            ("check", "/tʃek/", "verb", "✔️", "to examine to determine accuracy or quality", "ពិនិត្យ", "Check your answers before submitting.", "ពិនិត្យមើលចម្លើយរបស់អ្នកមុនពេលបញ្ជូន។"),
            ("lunch", "/lʌntʃ/", "noun", "🍱", "a meal eaten in the middle of the day", "អាហារថ្ងៃត្រង់", "What do you want to eat for lunch?", "តើអ្នកចង់ញ៉ាំអ្វីសម្រាប់អាហារថ្ងៃត្រង់?"),
            ("bench", "/bentʃ/", "noun", "🪵", "a long seat for several people", "បង់អង្គុយ", "They sat on a park bench.", "ពួកគេអង្គុយលើបង់សួនច្បារ។"),
            ("she", "/ʃiː/", "pronoun", "👩", "the female person referred to", "នាង", "She is a very smart student.", "នាងគឺជាសិស្សម្នាក់ដ៏ឆ្លាតវៃ។"),
            ("ship", "/ʃɪp/", "noun", "🚢", "a large boat for transporting goods or people", "នាវា", "The large ship sailed across the ocean.", "នាវាដ៏ធំបានបើកក្តោងឆ្លងកាត់មហាសមុទ្រ។"),
            ("fish", "/fɪʃ/", "noun", "🐟", "limbless cold-blooded animal living in water", "ត្រី", "A colorful fish swam in the pond.", "ត្រីចម្រុះពណ៌កំពុងហែលនៅក្នុងស្រះ។"),
            ("brush", "/brʌʃ/", "noun", "🪥", "tool with bristles for cleaning or grooming", "ច្រាស", "Use a soft brush for your teeth.", "ប្រើច្រាសទន់សម្រាប់ធ្មេញរបស់អ្នក។"),
            ("dish", "/dɪʃ/", "noun", "🍽️", "a flat plate or bowl for serving food", "ចាន", "Put the clean dish on the table.", "ដាក់ចានស្អាតនៅលើតុ។"),
            ("shell", "/ʃel/", "noun", "🐚", "hard outer covering of a mollusk or animal", "សំបកខ្ចៅ", "I found a beautiful shell on the beach.", "ខ្ញុំបានរកឃើញសំបកខ្ចៅដ៏ស្រស់ស្អាតនៅលើឆ្នេរខ្សាច់។"),
            ("shop", "/ʃɒp/", "noun", "🏪", "a building or room where goods are sold", "ហាង", "We went to the grocery shop.", "ពួកយើងបានទៅហាងលក់គ្រឿងទេស។"),
            ("shoe", "/ʃuː/", "noun", "👟", "a covering for the foot worn outside", "ស្បែកជើង", "Tie the laces of your running shoe.", "ចងខ្សែស្បែកជើងរត់របស់អ្នក។"),
            ("wash", "/wɒʃ/", "verb", "🧼", "to clean with water and soap", "លាង/បោកគក់", "Wash your hands before eating.", "លាងដៃរបស់អ្នកមុនពេលញ៉ាំអាហារ។"),
            ("crash", "/kræʃ/", "noun", "💥", "a violent collision or noise", "ការបុកគ្នា/សំឡេងខ្លាំង", "We heard a loud crash on the street.", "ពួកយើងបានឮសំឡេងបុកគ្នាយ៉ាងខ្លាំងនៅលើផ្លូវ។"),
            ("thin", "/θɪn/", "adjective", "🧍", "having opposite surfaces close together; lean", "ស្តើង/ស្គម", "He wrote on a thin sheet of paper.", "គាត់បានសរសេរនៅលើក្រដាសស្តើងមួយសន្លឹក។"),
            ("think", "/θɪŋk/", "verb", "🧠", "to use one's mind to form ideas", "គិត", "Think carefully before choosing the answer.", "គិតឱ្យបានច្បាស់មុនពេលជ្រើសរើសចម្លើយ។"),
            ("with", "/wɪð/", "preposition", "👥", "accompanied by; using a tool", "ជាមួយ", "I went to the library with my friend.", "ខ្ញុំបានទៅបណ្ណាល័យជាមួយមិត្តភក្តិរបស់ខ្ញុំ។"),
            ("bath", "/bæθ/", "noun", "🛁", "washing of the body in a tub of water", "ការងូតទឹក", "Take a warm bath after a long day.", "ងូតទឹកក្តៅឧណ្ហៗបន្ទាប់ពីថ្ងៃដ៏មមាញឹក។"),
            ("path", "/pæθ/", "noun", "🚶", "a track laid down for walking or cycling", "ផ្លូវដើរ", "Follow the narrow path through the woods.", "ដើរតាមផ្លូវតូចចង្អៀតកាត់ព្រៃ។"),
            ("tooth", "/tuːθ/", "noun", "🦷", "hard bony structure in the jaw used for biting", "ធ្មេញ", "Brush each tooth twice a day.", "ដុសធ្មេញនីមួយៗឱ្យបានពីរដងក្នុងមួយថ្ងៃ។"),
            ("moth", "/mɒθ/", "noun", "🦋", "an insect resembling a butterfly active at night", "មេអំបៅយប់", "A small moth flew around the bright light.", "មេអំបៅយប់តូចមួយបានហើរជុំវិញភ្លើងភ្លឺ។"),
            ("three", "/θriː/", "number", "3️⃣", "equivalent to the sum of two and one", "បី", "There are three birds in the nest.", "មានបក្សីបីក្បាលនៅក្នុងសំបុក។"),
            ("whale", "/weɪl/", "noun", "🐋", "a very large marine mammal", "ត្រីបាឡែន", "The blue whale is the largest animal.", "ត្រីបាឡែនពណ៌ខៀវគឺជាសត្វដែលធំបំផុត។"),
            ("white", "/waɪt/", "adjective", "⚪", "the color of fresh snow or milk", "ពណ៌ស", "The nurse wore a clean white coat.", "គិលានុបដ្ឋាយិកាបានពាក់អាវធំពណ៌សស្អាត។"),
            ("whip", "/wɪp/", "noun", "🪢", "a strip of leather used for driving animals", "រំពាត់", "The rider used a light whip.", "អ្នកជិះសេះបានប្រើរំពាត់ស្រាល។"),
            ("wheel", "/wiːl/", "noun", "🛞", "a circular object that revolves on an axle", "កង់ឡាន/ម៉ូតូ", "The car has a flat wheel.", "ឡានមានកង់ធ្លាយខ្យល់មួយ។"),
            ("when", "/wen/", "adverb", "❓", "at what time", "នៅពេលណា", "When will the school bell ring?", "តើជួងសាលានឹងរោទ៍នៅពេលណា?"),
            ("where", "/weər/", "adverb", "📍", "in or to what place", "នៅឯណា", "Where is my English textbook?", "តើសៀវភៅសិក្សាភាសាអង់គ្លេសរបស់ខ្ញុំនៅឯណា?"),
            ("wheat", "/wiːt/", "noun", "🌾", "a cereal grain used to make flour for bread", "ស្រូវសាលី", "The farmer grows golden wheat.", "កសិករដាំស្រូវសាលីពណ៌មាស។"),
            ("phone", "/foʊn/", "noun", "📱", "a telephone or smartphone device", "ទូរស័ព្ទ", "Answer the ringing phone.", "ឆ្លើយទូរស័ព្ទដែលកំពុងរោទ៍។"),
            ("photo", "/foʊtoʊ/", "noun", "📷", "a photograph taken with a camera", "រូបថត", "He took a beautiful photo of the sunset.", "គាត់បានថតរូបថ្ងៃលិចដ៏ស្រស់ស្អាតមួយ។"),
            ("phase", "/feɪz/", "noun", "🌗", "a distinct stage of development", "ដំណាក់កាល", "The project is in its final phase.", "គម្រោងនេះស្ថិតក្នុងដំណាក់កាលចុងក្រោយរបស់ខ្លួន។"),
            ("graph", "/ɡræf/", "noun", "📊", "a diagram showing relation of variable quantities", "ក្រាហ្វ", "Look at the bar graph in the book.", "មើលក្រាហ្វដុំនៅក្នុងសៀវភៅ។"),
            ("dolphin", "/ˈdɒlfɪn/", "noun", "🐬", "a small toothed whale known for intelligence", "ផ្សោត", "A dolphin leaped out of the ocean water.", "ផ្សោតមួយក្បាលបានលោតចេញពីទឹកមហាសមុទ្រ។"),
            ("duck", "/dʌk/", "noun", "🦆", "a waterbird with webbed feet and broad bill", "ទា", "The yellow duck swam in the pond.", "ទាពណ៌លឿងកំពុងហែលនៅក្នុងស្រះ។"),
            ("neck", "/nek/", "noun", "🦒", "the part of the body connecting head and torso", "ក", "The giraffe has a very long neck.", "សត្វក giraffe មានកវែងណាស់។"),
            ("sick", "/sɪk/", "adjective", "🤒", "affected by physical or mental illness", "ឈឺ", "He stayed home because he was sick.", "គាត់បាននៅផ្ទះដោយសារតែគាត់ឈឺ។"),
            ("rock", "/rɒk/", "noun", "🪨", "solid mineral material forming part of Earth", "ថ្ម", "He threw a small rock into the river.", "គាត់បានបោះថ្មតូចមួយចូលទៅក្នុងទន្លេ។"),
            ("sock", "/sɒk/", "noun", "🧦", "garment for the foot worn inside a shoe", "ស្រោមជើង", "Put on a warm wool sock.", "ពាក់ស្រោមជើងរោមចៀមដ៏កក់ក្តៅ។"),
            ("ring", "/rɪŋ/", "noun", "💍", "a circular band worn on a finger as jewelry", "ចិញ្ចៀន", "She wore a shiny gold ring.", "នាងបានពាក់ចិញ្ចៀនមាសដ៏ភ្លឺចែងចាំង។"),
            ("sing", "/sɪŋ/", "verb", "🎤", "to make musical sounds with the voice", "ច្រៀង", "She likes to sing sweet songs.", "នាងចូលចិត្តច្រៀងចម្រៀងដ៏ពិរោះ។"),
            ("song", "/sɒŋ/", "noun", "🎵", "a short poem or set of words set to music", "ចម្រៀង", "We listened to a happy song.", "ពួកយើងបានស្តាប់ចម្រៀងដ៏រីករាយមួយ។"),
            ("king", "/kɪŋ/", "noun", "👑", "the male ruler of an independent state", "ស្តេច", "The king wore a heavy gold crown.", "ព្រះរាជាបានពាក់មកុដមាសដ៏ធ្ងន់។"),
            ("wing", "/wɪŋ/", "noun", "🪶", "the limb of a bird or insect used for flying", "ស្លាប", "The eagle has a strong wing.", "សត្វឥន្ទ្រីមានស្លាបដ៏រឹងមាំ។")
        ]
    },
    # CATEGORY 4: Consonant Blends (50 words)
    {
        "category": "Consonant Blends",
        "words": [
            ("black", "/blæk/", "adjective", "⚫", "the darkest color, like coal or night", "ពណ៌ខ្មៅ", "She wore a elegant black dress.", "នាងបានពាក់អាវរ៉ូបពណ៌ខ្មៅដ៏ស្រស់ស្អាត។"),
            ("blow", "/bloʊ/", "verb", "💨", "to expel air from the mouth; wind current", "ផ្លុំ/បក់", "Blow out the candles on the cake.", "ផ្លុំពន្លត់ទៀននៅលើនំខេក។"),
            ("blue", "/bluː/", "adjective", "🔵", "the color of the sky or ocean", "ពណ៌ខៀវ", "She has bright blue eyes.", "នាងមានភ្នែកពណ៌ខៀវភ្លឺ។"),
            ("blind", "/blaɪnd/", "adjective", "🕶️", "unable to see", "ងងឹតភ្នែក", "The blind man walked with a guide dog.", "បុរសងងឹតភ្នែកបានដើរជាមួយឆ្កែនាំផ្លូវ។"),
            ("clay", "/kleɪ/", "noun", "🧱", "sticky earthy material used for pottery", "ដីឥដ្ឋ", "She molded a small cup out of clay.", "នាងបានសូនពែងតូចមួយពីដីឥដ្ឋ។"),
            ("clean", "/kliːn/", "adjective", "🧼", "free from dirt or marks", "ស្អាត", "Keep your study desk neat and clean.", "រក្សាតុសិក្សារបស់អ្នកឱ្យមានរបៀបនិងស្អាត។"),
            ("clock", "/klɒk/", "noun", "⏰", "device used to measure and show time", "នាឡិកា", "The wall clock says it is noon.", "នាឡិកាជញ្ជាំងបង្ហាញថាវាជាម៉ោងថ្ងៃត្រង់ហើយ។"),
            ("class", "/klæs/", "noun", "🏫", "a group of students taught together", "ថ្នាក់រៀន", "The English class starts at 8 AM.", "ថ្នាក់រៀនភាសាអង់គ្លេសចាប់ផ្តើមនៅម៉ោង ៨ ព្រឹក។"),
            ("fly", "/flaɪ/", "verb", "🪰", "to move through the air using wings", "ហើរ/រុយ", "Birds can fly high in the air.", "បក្សីអាចហោះហើរបានខ្ពស់នៅលើអាកាស។"),
            ("flat", "/flæt/", "adjective", "📏", "having a level surface without raised parts", "សំប៉ែត/រាបស្មើ", "The paper lies flat on the desk.", "ក្រដាសដេករាបស្មើនៅលើតុ។"),
            ("flag", "/flæɡ/", "noun", "🚩", "piece of cloth with a distinctive design as a symbol", "ទង់ជាតិ", "They raised the national flag.", "ពួកគេបានបង្ហូតទង់ជាតិ។"),
            ("float", "/floʊt/", "verb", "⛵", "to rest on the surface of liquid without sinking", "អណ្តែត", "Wood blocks float on water.", "ដុំឈើអណ្តែតលើទឹក។"),
            ("glad", "/ɡlæd/", "adjective", "😊", "feeling pleasure or happiness", "រីករាយ/សប្បាយចិត្ត", "I am glad to meet you today.", "ខ្ញុំរីករាយណាស់ដែលបានជួបអ្នកនៅថ្ងៃនេះ។"),
            ("glass", "/ɡlæs/", "noun", "🥛", "hard transparent material; drinking container", "កែវ/កញ្ចក់", "Pour some fresh water into the glass.", "ចាក់ទឹកស្អាតចូលក្នុងកែវ។"),
            ("globe", "/ɡloʊb/", "noun", "🌐", "spherical representation of the earth", "ភពផែនដី/លំហ", "Look at the country on the globe.", "មើលប្រទេសនៅលើភពផែនដី។"),
            ("glove", "/ɡlʌv/", "noun", "🧤", "covering for the hand with separate sheath for fingers", "ស្រោមដៃ", "Wear a thick glove in winter.", "ពាក់ស្រោមដៃក្រាស់ក្នុងរដូវរងា។"),
            ("play", "/pleɪ/", "verb", "🧸", "engage in activity for enjoyment rather than work", "លេង", "The kids like to play in the yard.", "ក្មេងៗចូលចិត្តលេងនៅក្នុងទីធ្លា។"),
            ("plan", "/plæn/", "noun", "🗺️", "a detailed proposal for doing something", "ផែនការ", "Let's make a study plan for exams.", "តោះបង្កើតផែនការសិក្សាសម្រាប់ការប្រឡង។"),
            ("plum", "/plʌm/", "noun", "🍑", "an oval fleshy fruit that is purple or reddish", "ផ្លែពុទ្រាអឺរ៉ុប", "The sweet purple plum was delicious.", "ផ្លែពុទ្រាអឺរ៉ុបពណ៌ស្វាយដ៏ផ្អែមពិតជាឆ្ងាញ់ណាស់។"),
            ("plant", "/plænt/", "noun", "🌱", "living organism absorbing water through roots", "រុក្ខជាតិ", "Water the green plant daily.", "ស្រោចទឹករុក្ខជាតិពណ៌បៃតងរៀងរាល់ថ្ងៃ។"),
            ("sleep", "/sliːp/", "verb", "💤", "to rest in unconscious state daily", "គេង", "Get enough sleep to stay healthy.", "គេងឱ្យបានគ្រប់គ្រាន់ដើម្បីរក្សាសុខភាព។"),
            ("slow", "/sloʊ/", "adjective", "🐢", "moving or operating at low speed", "យឺត", "The slow turtle walked on the path.", "អណ្តើកយឺតកំពុងដើរនៅលើផ្លូវ។"),
            ("slide", "/slaɪd/", "noun", "🛝", "a play structure with a smooth sloping surface", "រំអិល", "The kids ran to play on the slide.", "ក្មេងៗបានរត់ទៅលេងនៅលើកន្លែងរំអិល។"),
            ("slip", "/slɪp/", "verb", "🍌", "to slide accidentally and lose balance", "រអិល", "Be careful not to slip on the wet floor.", "ប្រយ័ត្នកុំឱ្យរអិលនៅលើឥដ្ឋសើម។"),
            ("brown", "/braʊn/", "adjective", "🟫", "color of wood or chocolate", "ពណ៌ត្នោត", "A small brown dog barked at us.", "ឆ្កែតូចពណ៌ត្នោតមួយក្បាលបានព្រុសដាក់យើង។"),
            ("bread", "/bred/", "noun", "🍞", "food made of flour, water, and yeast baked", "នំប៉័ង", "He spread butter on the bread.", "គាត់បានលាបប៊ឺនៅលើនំប៉័ង។"),
            ("brush", "/brʌʃ/", "verb", "🪥", "to clean or groom with a brush", "ដុសខាត់", "Brush your teeth in the morning.", "ដុសធ្មេញរបស់អ្នកនៅពេលព្រឹក។"),
            ("brave", "/breɪv/", "adjective", "🦁", "ready to face danger without fear", "ក្លាហាន", "The brave boy saved the puppy.", "ប្រុសក្លាហានបានសង្គ្រោះកូនឆ្កែ។"),
            ("cry", "/kraɪ/", "verb", "😭", "to shed tears from sadness or pain", "យំ", "The baby began to cry.", "ទារកបានចាប់ផ្តើមយំ។"),
            ("crab", "/kræb/", "noun", "🦀", "a shellfish with ten legs and claws", "ក្តាម", "The red crab walked sideways on the sand.", "ក្តាមពណ៌ក្រហមបានដើរទៅចំហៀងនៅលើខ្សាច់។"),
            ("crop", "/krɒp/", "noun", "🌾", "cultivated plant grown as food", "ដំណាំ", "The corn crop is ready to harvest.", "ដំណាំពោតរួចរាល់សម្រាប់ប្រមូលផលហើយ។"),
            ("crown", "/kraʊn/", "noun", "👑", "ornamental headdress worn by a monarch", "មកុដ", "The queen has a sparkling crown.", "ម្ចាស់ក្សត្រីមានមកុដដ៏ភ្លឺចែងចាំង។"),
            ("drum", "/drʌm/", "noun", "🥁", "percussion instrument played with sticks", "ស្គរ", "He played the drum in the school band.", "គាត់បានលេងស្គរនៅក្នុងក្រុមតន្ត្រីសាលា។"),
            ("drop", "/drɒp/", "verb", "💧", "to let fall vertically; a small round quantity of liquid", "ទម្លាក់/តំណក់", "Don't drop the glass, it will break.", "កុំទម្លាក់កែវឱ្យសោះ វានឹងបែក។"),
            ("drink", "/drɪŋk/", "verb", "🥛", "take liquid into the mouth and swallow", "ផឹក", "Drink a glass of water every morning.", "ផឹកទឹកមួយកែវរៀងរាល់ព្រឹក។"),
            ("dress", "/dres/", "noun", "👗", "one-piece garment worn by women or girls", "សម្លៀកបំពាក់រ៉ូប", "She wore a pretty pink dress.", "នាងបានពាក់សម្លៀកបំពាក់រ៉ូបពណ៌ផ្កាឈូកដ៏ស្រស់ស្អាត។"),
            ("frog", "/frɒɡ/", "noun", "🐸", "tailless amphibian with long hind legs for leaping", "កង្កែប", "The green frog jumped into the pond.", "កង្កែបពណ៌បៃតងបានលោតចូលទៅក្នុងស្រះ។"),
            ("free", "/friː/", "adjective", "🕊️", "not under control; costing no money", "សេរី/ឥតគិតថ្លៃ", "The bird is free to fly.", "បក្សីមានសេរីភាពក្នុងការហោះហើរ។"),
            ("fruit", "/fruːt/", "noun", "🍇", "sweet seed-bearing product of a plant", "ផ្លែឈើ", "We buy fresh fruit from the market.", "ពួកយើងទិញផ្លែឈើស្រស់ពីផ្សារ។"),
            ("fresh", "/freʃ/", "adjective", "🍎", "recently made, clean, or harvested", "ស្រស់", "I love the smell of fresh bread.", "ខ្ញុំចូលចិត្តក្លិននំប៉័ងស្រស់ណាស់។"),
            ("green", "/ɡriːn/", "adjective", "🟢", "color of leaves or emeralds", "ពណ៌បៃតង", "The fields are green in spring.", "វាលស្រែមានពណ៌បៃតងនៅរដូវផ្ការីក។"),
            ("grass", "/ɡræs/", "noun", "🌱", "common wild plant with narrow leaves", "ស្មៅ", "We sat on the soft grass.", "ពួកយើងបានអង្គុយនៅលើស្មៅដ៏ទន់។"),
            ("grow", "/ɡroʊ/", "verb", "📈", "to increase in size or develop", "លូតលាស់/ដុះ", "Plants need water to grow.", "រុក្ខជាតិត្រូវការទឹកដើម្បីលូតលាស់។"),
            ("grape", "/ɡreɪp/", "noun", "🍇", "sweet berry growing in bunches", "ផ្លែទំពាំងបាយជូរ", "He picked a bunch of grape.", "គាត់បានបេះផ្លែទំពាំងបាយជូរមួយចង្កោម។"),
            ("press", "/pres/", "verb", "👉", "to apply force or push a button", "សង្កត់/ចុច", "Press the button to play the sound.", "ចុចប៊ូតុងដើម្បីលេងសំឡេង។"),
            ("prize", "/praɪz/", "noun", "🏆", "award given as a reward for victory", "រង្វាន់", "He won first prize in the quiz.", "គាត់បានឈ្នះរង្វាន់ទីមួយនៅក្នុងការសាកល្បងចំណេះដឹង។"),
            ("proud", "/praʊd/", "adjective", "😊", "feeling deep pleasure or satisfaction in achievements", "មោទនភាព", "His parents are proud of his grades.", "ឪពុកម្តាយរបស់គាត់មានមោទនភាពចំពោះពិន្ទុរបស់គាត់។"),
            ("tree", "/triː/", "noun", "🌳", "tall plant with woody trunk and branches", "ដើមឈើ", "The mango tree has sweet fruit.", "ដើមស្វាយមានផ្លែផ្អែម។"),
            ("train", "/treɪn/", "noun", "🚆", "railway carriages pulled by an engine", "រថភ្លើង", "The train arrived at the station.", "រថភ្លើងបានមកដល់ស្ថានីយ។"),
            ("trip", "/trɪp/", "noun", "🎒", "a journey or excursion", "ដំណើរកំសាន្ត", "We went on a school trip to the museum.", "ពួកយើងបានទៅដំណើរកំសាន្តសាលាទៅសារមន្ទីរ។")
        ]
    },
    # CATEGORY 5: Diphthongs & Special Vowels (50 words)
    {
        "category": "Diphthongs & Special Vowels",
        "words": [
            ("book", "/bʊk/", "noun", "📖", "written or printed work consisting of pages", "សៀវភៅ", "Read an interesting book today.", "អានសៀវភៅដែលគួរឱ្យចាប់អារម្មណ៍នៅថ្ងៃនេះ។"),
            ("look", "/lʊk/", "verb", "👀", "direct one's gaze toward someone or something", "មើល", "Look at the colorful butterfly.", "មើលមេអំបៅចម្រុះពណ៌នោះមើល។"),
            ("good", "/ɡʊd/", "adjective", "👍", "to be desired or approved of; high quality", "ល្អ", "Eating fruit is good for your health.", "ការញ៉ាំផ្លែឈើគឺល្អសម្រាប់សុខភាពរបស់អ្នក។"),
            ("foot", "/fʊt/", "noun", "🦶", "lower extremity of the leg below ankle", "ជើង", "He kicked the ball with his right foot.", "គាត់បានទាត់បាល់ដោយជើងស្តាំរបស់គាត់។"),
            ("wood", "/wʊd/", "noun", "🪵", "hard fibrous material of tree trunks", "ឈើ", "The table is made of solid wood.", "តុនេះធ្វើពីឈើរឹង។"),
            ("cook", "/kʊk/", "verb", "🍳", "prepare food by heating it", "ចម្អិន", "My father likes to cook dinner.", "ឪពុករបស់ខ្ញុំចូលចិត្តចម្អិនអាហារពេលល្ងាច។"),
            ("hook", "/hʊk/", "noun", "🪝", "curved piece of metal used for catching or holding", "ទំពក់", "Hang your coat on the wall hook.", "ព្យួរអាវធំរបស់អ្នកនៅលើទំពក់ជញ្ជាំង។"),
            ("hood", "/hʊd/", "noun", "🧥", "covering for the head attached to a coat", "មួកអាវធំ", "Pull up your hood, it is raining.", "ទាញមួកអាវធំរបស់អ្នកឡើង ភ្លៀងកំពុងធ្លាក់ហើយ។"),
            ("food", "/fuːd/", "noun", "🍱", "substance consumed to maintain life and growth", "អាហារ", "Fresh food is delicious and healthy.", "អាហារស្រស់គឺពិរោះនិងមានសុខភាពល្អ។"),
            ("moon", "/muːn/", "noun", "🌙", "natural satellite of the earth shining at night", "ព្រះច័ន្ទ", "The moon shines brightly at night.", "ព្រះច័ន្ទរះភ្លឺចែងចាំងនៅពេលយប់។"),
            ("spoon", "/spuːn/", "noun", "🥄", "utensil consisting of a small shallow bowl with handle", "ស្លាបព្រា", "Eat your warm soup with a spoon.", "ញ៉ាំស៊ុបក្តៅរបស់អ្នកដោយប្រើស្លាបព្រា។"),
            ("pool", "/puːl/", "noun", "🏊", "artificial pool of water for swimming", "អាងហែលទឹក", "We swam in the swimming pool.", "ពួកយើងបានហែលទឹកនៅក្នុងអាងហែលទឹក។"),
            ("cool", "/kuːl/", "adjective", "🌬️", "moderately cold; calm or fashionable", "ត្រជាក់/ឡូយ", "A cool breeze blew in the evening.", "ខ្យល់ត្រជាក់បក់បោកនៅពេលល្ងាច។"),
            ("tool", "/tuːl/", "noun", "🔨", "device or implement used to carry out a process", "ឧបករណ៍", "A hammer is a useful tool.", "ញញួរគឺជាឧបករណ៍ដែលមានប្រយោជន៍។"),
            ("boy", "/bɔɪ/", "noun", "👦", "a male child", "ក្មេងប្រុស", "The boy ran to catch the ball.", "ក្មេងប្រុសបានរត់ទៅចាប់បាល់។"),
            ("toy", "/tɔɪ/", "noun", "🧸", "object for a child to play with", "ប្រដាប់ក្មេងលេង", "He shared his favorite toy with his friend.", "គាត់បានចែករំលែកប្រដាប់ក្មេងលេងដែលគាត់ចូលចិត្តជាមួយមិត្តភក្តិ។"),
            ("joy", "/dʒɔɪ/", "noun", "😊", "feeling of great pleasure and happiness", "សេចក្តីរីករាយ", "Her heart was filled with joy.", "បេះដូងរបស់នាងពោរពេញទៅដោយសេចក្តីរីករាយ។"),
            ("enjoy", "/ɪnˈdʒɔɪ/", "verb", "🥰", "take delight or pleasure in", "រីករាយនឹង", "We enjoy playing under the sun.", "ពួកយើងរីករាយនឹងការលេងនៅក្រោមពន្លឺថ្ងៃ។"),
            ("annoy", "/əˈnɔɪ/", "verb", "😠", "make slightly angry or irritated", "រំខាន/ធ្វើឱ្យខឹង", "The loud noise began to annoy him.", "សំឡេងខ្លាំងបានចាប់ផ្តើមធ្វើឱ្យគាត់រំខាន។"),
            ("join", "/dʒɔɪn/", "verb", "🤝", "link or connect together; become a member", "ចូលរួម", "Would you like to join our game?", "តើអ្នកចង់ចូលរួមល្បែងរបស់យើងទេ?"),
            ("coin", "/kɔɪn/", "noun", "🪙", "flat disc of metal used as money", "កាក់", "He found a shiny gold coin.", "គាត់បានរកឃើញកាក់មាសដ៏ភ្លឺចែងចាំងមួយ។"),
            ("oil", "/ɔɪl/", "noun", "🛢️", "smooth thick liquid used for cooking or fuel", "ប្រេង", "Add a drop of olive oil to the salad.", "បន្ថែមប្រេងអូលីវមួយតំណក់ទៅក្នុងសាឡាត់។"),
            ("soil", "/sɔɪl/", "noun", "🌱", "upper layer of earth in which plants grow", "ដីដាំដុះ", "Put the seeds in the rich soil.", "ដាក់គ្រាប់ពូជទៅក្នុងដីដាំដុះដ៏មានជីវជាតិ។"),
            ("point", "/pɔɪnt/", "verb", "👉", "direct someone's attention by extending a finger", "ចង្អុល", "Point to the correct picture.", "ចង្អុលទៅរូបភាពដែលត្រឹមត្រូវ។"),
            ("noise", "/nɔɪz/", "noun", "🔊", "a sound, especially one that is loud or unpleasant", "សំឡេងរំខាន", "The traffic makes a lot of noise.", "ចរាចរណ៍បង្កើតសំឡេងរំខានជាច្រើន។"),
            ("voice", "/vɔɪs/", "noun", "🗣️", "sound produced in a person's larynx and uttered", "សំឡេង", "She speaks in a soft, clear voice.", "នាងនិយាយដោយសំឡេងទន់ភ្លន់និងច្បាស់លាស់។"),
            ("house", "/haʊs/", "noun", "🏠", "building for human habitation", "ផ្ទះ", "They live in a beautiful house.", "ពួកគេរស់នៅក្នុងផ្ទះដ៏ស្រស់ស្អាតមួយ។"),
            ("mouse", "/maʊs/", "noun", "🐭", "small rodent with pointed snout and long tail", "កណ្តុរ", "A tiny mouse hid behind the box.", "កណ្តុរតូចមួយបានលាក់ខ្លួននៅពីក្រោយប្រអប់។"),
            ("mouth", "/maʊθ/", "noun", "👄", "opening in the face through which food is taken", "មាត់", "Chew your food with your mouth closed.", "ទំពារអាហាររបស់អ្នកដោយបិទមាត់។"),
            ("cloud", "/klaʊd/", "noun", "☁️", "visible mass of condensed water vapor in the sky", "ពពក", "A white cloud floated in the sky.", "ពពកពណ៌សបានអណ្តែតលើមេឃ។"),
            ("round", "/raʊnd/", "adjective", "⭕", "shaped like a circle or cylinder", "មូល", "The children sat in a round circle.", "ក្មេងៗបានអង្គុយជារង្វង់មូល។"),
            ("out", "/aʊt/", "adverb", "🚪", "away from or not inside a place", "ខាងក្រៅ", "He walked out of the classroom.", "គាត់បានដើរចេញពីថ្នាក់រៀន។"),
            ("shout", "/ʃaʊt/", "verb", "🗣️", "speak or cry out loudly and vociferously", "ស្រែក", "Don't shout in the quiet library.", "កុំស្រែកនៅក្នុងបណ្ណាល័យដ៏ស្ងប់ស្ងាត់។"),
            ("proud", "/praʊd/", "adjective", "😊", "feeling satisfaction in achievements", "មោទនភាព", "I am proud of my exam results.", "ខ្ញុំមានមោទនភាពចំពោះលទ្ធផលប្រឡងរបស់ខ្ញុំ។"),
            ("cow", "/kaʊ/", "noun", "🐄", "fully grown female domestic animal kept for milk", "មេគោ", "The black and white cow eats grass.", "មេគោពណ៌ខ្មៅនិងសកំពុងស៊ីស្មៅ។"),
            ("how", "/haʊ/", "adverb", "❓", "in what way or manner", "ដូចម្តេច", "How do you spell your nickname?", "តើអ្នកសរសេររហស្សនាមរបស់អ្នកដូចម្តេច?"),
            ("now", "/naʊ/", "adverb", "⏰", "at the present time", "ឥឡូវនេះ", "We must start our homework now.", "พวกយើងត្រូវតែចាប់ផ្តើមកិច្ចការផ្ទះឥឡូវនេះ។"),
            ("town", "/taʊn/", "noun", "🏙️", "urban area smaller than a city", "ទីប្រជុំជន", "We visited a small historic town.", "ពួកយើងបានទៅលេងទីប្រជុំជនប្រវត្តិសាស្ត្រតូចមួយ។"),
            ("down", "/daʊn/", "adverb", "⬇️", "toward a lower place or position", "ចុះក្រោម", "Sit down on the floor, please.", "សូមអង្គុយចុះនៅលើឥដ្ឋ។"),
            ("brown", "/braʊn/", "adjective", "🟫", "color of earth or wood", "ពណ៌ត្នោត", "The brown leaves fell in autumn.", "ស្លឹកឈើពណ៌ត្នោតបានជ្រុះនៅរដូវស្លឹកឈើជ្រុះ។"),
            ("draw", "/drɔː/", "verb", "🎨", "produce a picture or diagram with pencil", "គូរ", "She likes to draw beautiful landscapes.", "នាងចូលចិត្តគូររូបភាពទេសភាពដ៏ស្រស់ស្អាត។"),
            ("saw", "/sɔː/", "verb", "🪚", "past form of see; hand tool for cutting wood", "បានឃើញ/អារឈើ", "He saw a beautiful bird; cut wood with a saw.", "គាត់បានឃើញបក្សីដ៏ស្រស់ស្អាតមួយ; អារឈើដោយប្រើអាណា។"),
            ("jaw", "/dʒɔː/", "noun", "🧔", "bony structure in which teeth are set", "ថ្គាម/ឆ្អឹងថ្គាម", "His jaw hurt after chewing the hard meat.", "ថ្គាមរបស់គាត់ឈឺបន្ទាប់ពីទំពារសាច់រឹង។"),
            ("law", "/lɔː/", "noun", "⚖️", "system of rules regulated by a community", "ច្បាប់", "Everyone must follow the traffic law.", "គ្រប់គ្នាត្រូវតែគោរពច្បាប់ចរាចរណ៍។"),
            ("raw", "/rɔː/", "adjective", "🥩", "uncooked food; in natural state", "ឆៅ", "You should not eat raw chicken.", "អ្នកមិនគួរញ៉ាំសាច់មាន់ឆៅទេ។"),
            ("straw", "/strɔː/", "noun", "🥤", "thin paper or plastic tube for sucking drink", "ទុយោ", "Sip your cold juice through a straw.", "បឺតទឹកផ្លែឈើត្រជាក់របស់អ្នកតាមទុយោ។"),
            ("claw", "/klɔː/", "noun", "🦅", "curved pointed horny nail on each digit of animal", "ក្រញ៉ាំជើងសត្វ", "The eagle caught a mouse in its sharp claw.", "សត្វឥន្ទ្រីបានចាប់កណ្តុរនៅក្នុងក្រញ៉ាំជើងដ៏មុតស្រួចរបស់វា។"),
            ("haul", "/hɔːl/", "verb", "🚚", "pull or drag with effort or force", "អូស/ដឹកជញ្ជូន", "Trucks haul heavy loads across the highway.", "ឡានដឹកទំនិញដឹកជញ្ជូនទំនិញធ្ងន់ៗកាត់តាមផ្លូវល្បឿនលឿន។"),
            ("fault", "/fɔːlt/", "noun", "⚠️", "responsibility for an accident or misfortune", "កំហុស", "It was my fault that the vase broke.", "វាជាកំហុសរបស់ខ្ញុំដែលធ្វើឱ្យថូផ្កាបែក។"),
            ("pause", "/pɔːz/", "verb", "⏸️", "temporary stop in action or speech", "ផ្អាក", "Pause the video to write notes.", "ផ្អាកវីដេអូដើម្បីសរសេរកំណត់ចំណាំ។")
        ]
    },
    # CATEGORY 6: R-Controlled Vowels (50 words)
    {
        "category": "R-Controlled Vowels",
        "words": [
            ("star", "/stɑːr/", "noun", "⭐", "fixed luminous point in the night sky", "ផ្កាយ", "A bright star shined in the night sky.", "ផ្កាយដ៏ភ្លឺចែងចាំងមួយបានរះលើមេឃយប់។"),
            ("park", "/pɑːrk/", "noun", "🏞️", "large public green area in a town for recreation", "សួនច្បារសាធារណៈ", "We walked our dog in the green park.", "ពួកយើងបាននាំឆ្កែដើរលេងនៅក្នុងសួនច្បារសាធារណៈ។"),
            ("dark", "/dɑːrk/", "adjective", "🌑", "with little or no light", "ងងឹត", "The room grew dark after sunset.", "បន្ទប់បានចាប់ផ្តើមងងឹតបន្ទាប់ពីថ្ងៃលិច។"),
            ("arm", "/ɑːrm/", "noun", "💪", "upper limb of the human body", "ដៃ", "He wore a watch on his left arm.", "គាត់បានពាក់នាឡិកានៅលើដៃឆ្វេងរបស់គាត់។"),
            ("farm", "/fɑːrm/", "noun", "🚜", "area of land used for growing crops and rearing animals", "កសិដ្ឋាន", "My uncle owns a large vegetable farm.", "ពូរបស់ខ្ញុំមានកសិដ្ឋានបន្លែដ៏ធំមួយ។"),
            ("card", "/kɑːrd/", "noun", "✉️", "piece of thick stiff paper for greetings or games", "កាត/សន្លឹកបៀ", "She wrote a beautiful greeting card.", "នាងបានសរសេរកាតជូនពរដ៏ស្រស់ស្អាតមួយ។"),
            ("yard", "/jɑːrd/", "noun", "🏡", "area of ground surrounding a building", "ទីធ្លាផ្ទះ", "The kids are playing in the front yard.", "ក្មេងៗកំពុងលេងនៅទីធ្លាមុខផ្ទះ។"),
            ("hard", "/hɑːrd/", "adjective", "🪨", "solid, firm, and rigid; difficult", "រឹង/ពិបាក", "The diamond is a very hard mineral.", "ពេជ្រគឺជាសារធាតុរ៉ែដ៏រឹងបំផុត។"),
            ("bark", "/bɑːrd/", "verb", "🔊", "sharp explosive cry of a dog; tough outer wood cover", "ព្រុស/សម្បកឈើ", "The neighbor's dogs bark at night.", "ឆ្កែរបស់អ្នកជិតខាងព្រុសនៅពេលយប់។"),
            ("chart", "/tʃɑːrt/", "noun", "📊", "sheet of information in the form of graph or diagram", "គំនូសតាង", "Study the growth chart on the board.", "សិក្សាគំនូសតាងលូតលាស់នៅលើក្តារខៀន។"),
            ("verb", "/vɜːrb/", "noun", "📝", "word used to describe an action or state", "កិរិយាសព្ទ", "A verb expresses action in a sentence.", "កិរិយាសព្ទបង្ហាញពីសកម្មភាពនៅក្នុងល្បះ។"),
            ("herd", "/hɜːrd/", "noun", "🐄", "large group of animals kept together", "ហ្វូងសត្វ", "A large herd of cows grazed in the valley.", "ហ្វូងគោដ៏ធំមួយកំពុងស៊ីស្មៅនៅក្នុងជ្រលងភ្នំ។"),
            ("term", "/term/", "noun", "📅", "a fixed period for which something lasts", "ឆមាស/រយៈពេល", "We have a break at the end of the school term.", "ពួកយើងមានពេលសម្រាកនៅចុងឆមាសសិក្សា។"),
            ("germ", "/dʒɜːrm/", "noun", "🦠", "microorganism that causes disease", "មេរោគ", "Wash your hands to remove any germ.", "លាងដៃរបស់អ្នកដើម្បីកម្ចាត់មេរោគ។"),
            ("bird", "/bɜːrd/", "noun", "🐦", "warm-blooded egg-laying vertebrate with feathers", "បក្សី/សត្វស្លាប", "A small blue bird sang a sweet song.", "បក្សីតូចពណ៌ខៀវមួយក្បាលបានច្រៀងចម្រៀងដ៏ពិរោះ។"),
            ("girl", "/ɡɜːrd/", "noun", "👧", "a female child", "ក្មេងស្រី", "The smart girl solved the math puzzle.", "ក្មេងស្រីដ៏ឆ្លាតវៃបានដោះស្រាយល្បែងផ្គុំរូបគណិតវិទ្យា។"),
            ("shirt", "/ʃɜːrt/", "noun", "👕", "garment for the upper part of the body", "អាវ", "He bought a new blue cotton shirt.", "គាត់បានទិញអាវកប្បាសពណ៌ខៀវថ្មីមួយ។"),
            ("dirt", "/dɜːrt/", "noun", "🟫", "loose soil or earth; unclean matter", "ដី/ធូលីដី", "His shoes were covered in wet dirt.", "ស្បែកជើងរបស់គាត់ត្រូវបានគ្របដណ្តប់ដោយដីសើម។"),
            ("skirt", "/skɜːrt/", "noun", "👗", "garment hanging from the waist worn by women", "សំពត់", "She wore a pleated blue skirt.", "នាងបានពាក់សំពត់ពណ៌ខៀវបត់ជើង។"),
            ("stir", "/stɜːr/", "verb", "🥄", "mix an ingredient by moving it around", "កូរ", "Stir the sugar into your tea.", "កូរស្ករចូលទៅក្នុងតែរបស់អ្នក។"),
            ("turn", "/tɜːrn/", "verb", "🔄", "move around a central point; change direction", "បត់/បង្វិល", "Turn left at the next street corner.", "បត់ឆ្វេងនៅជ្រុងផ្លូវបន្ទាប់។"),
            ("burn", "/bɜːrn/", "verb", "🔥", "consume or be consumed by fire", "ដុត/ឆេះ", "Be careful not to burn the toast.", "ប្រយ័ត្នកុំឱ្យឆេះនំប៉័ងអាំង។"),
            ("hurt", "/hɜːrt/", "verb", "🤕", "cause physical pain or injury to", "ឈឺចាប់/របួស", "He fell down and hurt his knee.", "គាត់បានដួលហើយរបួសជង្គង់របស់គាត់។"),
            ("fur", "/fɜːr/", "noun", "🦊", "short, fine, soft hair of certain animals", "រោមសត្វ", "The kitten has soft white fur.", "កូនឆ្មាមានរោមទន់ពណ៌ស។"),
            ("surf", "/sɜːrf/", "verb", "🏄", "ride on the crest of a wave towards shore", "ជិះរលក", "They love to surf in the ocean waves.", "ពួកគេចូលចិត្តជិះរលកនៅក្នុងរលកមហាសមុទ្រ។"),
            ("curl", "/sɜːrl/", "verb", "🌀", "form into a curved or spiral shape", "ធ្វើឱ្យរួញ", "Her hair began to curl in the damp air.", "សក់របស់នាងបានចាប់ផ្តើមរួញនៅក្នុងខ្យល់សើម។"),
            ("nurse", "/nɜːrs/", "noun", "🧑‍⚕️", "person trained to care for the sick", "គិលានុបដ្ឋាយិកា", "The friendly nurse checked my temperature.", "គិលានុបដ្ឋាយិកាដ៏រាក់ទាក់បានពិនិត្យសីតុណ្ហភាពរបស់ខ្ញុំ។"),
            ("purse", "/pɜːrs/", "noun", "👛", "small bag for carrying money or coins", "កាបូបលុយ", "She kept her coins in a small leather purse.", "នាងបានទុកកាក់របស់នាងនៅក្នុងកាបូបលុយស្បែកតូចមួយ។"),
            ("fork", "/fɔːrk/", "noun", "🍴", "pronged tool used for eating food", "សម", "Eat your pasta with a fork.", "ញ៉ាំប៉ាស្តារបស់អ្នកដោយប្រើសម។"),
            ("corn", "/kɔːrn/", "noun", "🌽", "cereal plant that yields large grains on cobs", "ពោត", "We boiled sweet yellow corn for dinner.", "ពួកយើងបានស្ងោរពោតលឿងផ្អែមសម្រាប់អាហារពេលល្ងាច។"),
            ("horn", "/hɔːrn/", "noun", "📯", "hard permanent projection on head of animals; instrument", "ស្នែងសត្វ/ស៊ីផ្លេ", "The deer has curved horn structures.", "សត្វក្តាន់មានរចនាសម្ព័ន្ធស្នែងកោង។"),
            ("short", "/ʃɔːrt/", "adjective", "📏", "measuring a small distance from end to end", "ខ្លី/ទាប", "He wrote a short English paragraph.", "គាត់បានសរសេរកថាខណ្ឌភាសាអង់គ្លេសខ្លីមួយ។"),
            ("storm", "/stɔːrm/", "noun", "⛈️", "violent disturbance of the atmosphere with rain/wind", "ព្យុះ", "The heavy storm blew down a big tree.", "ព្យុះដ៏ខ្លាំងបានបក់បោកដើមឈើធំមួយដួល។"),
            ("port", "/pɔːrt/", "noun", "⚓", "town or city with a harbor for ships", "កំពង់ផែ", "The cargo ships docked at the busy port.", "នាវាដឹកទំនិញបានចូលចតនៅកំពង់ផែដ៏មមាញឹក។"),
            ("fort", "/fɔːrt/", "noun", "🏰", "fortified building or strategic position", "បន្ទាយ", "The soldiers guarded the stone fort.", "ទាហានបានយាមបន្ទាយថ្ម។"),
            ("north", "/nɔːrθ/", "noun", "🧭", "direction that is to the left of sunrise", "ទិសខាងជើង", "The compass needle always points north.", "ទ្រនិចត្រីវិស័យតែងតែចង្អុលទៅទិសខាងជើង។"),
            ("south", "/saʊθ/", "noun", "🧭", "direction opposite of north", "ទិសខាងត្បូង", "Birds fly south for the winter.", "បក្សីហើរទៅទិសខាងត្បូងសម្រាប់រដូវរងា។"),
            ("art", "/ɑːrt/", "noun", "🎨", "expression of creative skill in visual form", "សិល្បៈ", "We created paintings in the art class.", "ពួកយើងបានបង្កើតគំនូរនៅក្នុងថ្នាក់សិល្បៈ។"),
            ("smart", "/smɑːrt/", "adjective", "🧠", "intelligent, clever, or neat", "ឆ្លាត", "She is a smart and polite student.", "នាងគឺជាសិស្សម្នាក់ដ៏ឆ្លាតវៃនិងគួរសម។"),
            ("tart", "/tɑːrt/", "noun", "🥧", "an open pastry case containing sweet filling", "នំតាត/នំកំសង់", "She baked a fresh strawberry tart.", "នាងបានដុតនំតាតស្ត្របឺរីស្រស់មួយ។"),
            ("cart", "/kɑːrt/", "noun", "🛒", "strong open vehicle with two or four wheels", "រទេះ", "Put the groceries in the shopping cart.", "ដាក់គ្រឿងទេសនៅក្នុងរទេះទិញទំនិញ។"),
            ("clerk", "/klɑːrk/", "noun", "🧑‍💼", "person employed in an office or shop to keep records", "បុគ្គលិកការិយាល័យ", "The hotel clerk gave us our room key.", "បុគ្គលិកសណ្ឋាគារបានផ្តល់សោបន្ទប់ឱ្យយើង។"),
            ("fern", "/fɜːrn/", "noun", "🌿", "flowerless plant with feathery green fronds", "រុក្ខជាតិបែកមែកធាង", "A large green fern grew in the wet forest.", "រុក្ខជាតិបែកមែកធាងពណ៌បៃតងដ៏ធំមួយបានដុះនៅក្នុងព្រៃសើម។"),
            ("birch", "/bɜːtʃ/", "noun", "🌳", "slender hardy deciduous tree with thin bark", "ដើមបឺក", "The birch tree has smooth white bark.", "ដើមបឺកមានសម្បកសរលោង។"),
            ("chirp", "/tʃɜːrp/", "verb", "🐦", "make a short, sharp, high-pitched sound", "យំ (ចាប)", "We heard the birds chirp in the morning.", "ពួកយើងបានឮសត្វចាបយំនៅពេលព្រឹក។"),
            ("first", "/fɜːrst/", "number", "1️⃣", "coming before all others in time or order", "ទីមួយ", "He won first place in the running race.", "គាត់បានឈ្នះលេខមួយក្នុងការប្រណាំងរត់។"),
            ("third", "/θɜːrd/", "number", "3️⃣", "constituting number three in a sequence", "ទីបី", "This is the third book in the series.", "នេះគឺជាសៀវភៅទីបីនៅក្នុងស៊េរី។"),
            ("thirst", "/θɜːrst/", "noun", "💧", "feeling of needing to drink liquid", "ការស្រេកទឹក", "A cold glass of water quenched his thirst.", "ទឹកត្រជាក់មួយកែវបានជួយកាត់បន្ថយការស្រេកទឹករបស់គាត់។"),
            ("curve", "/kɜːrv/", "noun", "彎", "a line or surface that bends continuously", "ផ្លូវកោង", "The road had a sharp curve on the hill.", "ផ្លូវមានផ្លូវកោងស្រួចនៅលើកូនភ្នំ។"),
            ("yard", "/jɑːrd/", "noun", "🏡", "area of ground surrounding a house", "ទីធ្លា", "We planted flowers in the front yard.", "ពួកយើងបានដាំផ្កានៅទីធ្លាមុខផ្ទះ។")
        ]
    },
    # CATEGORY 7: Silent Letters (50 words)
    {
        "category": "Silent Letters",
        "words": [
            ("knee", "/niː/", "noun", "🦵", "joint between the thigh and the lower leg", "ជង្គង់", "He scraped his knee when he fell.", "គាត់បានកោសជង្គង់របស់គាត់នៅពេលគាត់ដួល។"),
            ("knife", "/naɪf/", "noun", "🔪", "cutting tool with a sharp blade and handle", "កាំបិត", "Use a sharp knife to cut the apple.", "ប្រើកាំបិតមុតស្រួចដើម្បីកាត់ផ្លែប៉ោម។"),
            ("knot", "/nɒt/", "noun", "🪢", "fastening made by tying a piece of string", "ចំណង", "Tie a double knot in the rope.", "ចងចំណងពីរជាន់នៅក្នុងខ្សែពួរ។"),
            ("knit", "/nɪt/", "verb", "🧶", "make a garment by interlocking loops of wool", "ត្បាញ", "Her grandmother likes to knit warm sweaters.", "ជីដូនរបស់នាងចូលចិត្តត្បាញអាវរោមចៀមដ៏កក់ក្តៅ។"),
            ("knock", "/nɒk/", "verb", "🚪", "strike a surface noisily to attract attention", "គោះទ្វារ", "Knock on the door before entering.", "គោះទ្វារមុនពេលចូល។"),
            ("knew", "/njuː/", "verb", "🧠", "past form of know; possessed knowledge", "បានដឹង", "She knew the correct answer to the question.", "នាងបានដឹងចម្លើយត្រឹមត្រូវចំពោះសំណួរនេះ។"),
            ("knelt", "/nelt/", "verb", "🛐", "past form of kneel; supported weight on knees", "បានលុតជង្គង់", "He knelt down to tie his shoelaces.", "គាត់បានលុតជង្គង់ចុះដើម្បីចងខ្សែស្បែកជើងរបស់គាត់។"),
            ("kneel", "/niːl/", "verb", "🛐", "fall or rest on one's knees", "លុតជង្គង់", "The players kneel during the prayer.", "កីឡាករលុតជង្គង់ក្នុងអំឡុងពេលអធិស្ឋាន។"),
            ("knight", "/naɪt/", "noun", "🛡️", "historical soldier in armor serving a ruler", "អ្នកចម្បាំង", "The brave knight rode a black horse.", "អ្នកចម្បាំងក្លាហានបានជិះសេះពណ៌ខ្មៅ។"),
            ("knob", "/nɒb/", "noun", "🚪", "rounded button or handle on a door", "ក្បាលទ្វារ", "Turn the brass knob to open the door.", "បង្វិលក្បាលទ្វារលង្ហិនដើម្បីបើកទ្វារ។"),
            ("write", "/raɪt/", "verb", "📝", "mark letters on a surface with a pen", "សរសេរ", "Write a letter to your pen pal.", "សរសេរសំបុត្រទៅកាន់មិត្តភក្តិសំបុត្ររបស់អ្នក។"),
            ("wrist", "/rɪst/", "noun", "⌚", "joint connecting hand and forearm", "កដៃ", "He wore a digital watch on his wrist.", "គាត់បានពាក់នាឡិកាឌីជីថលនៅលើកដៃរបស់គាត់។"),
            ("wrong", "/rɒŋ/", "adjective", "❌", "incorrect or mistaken", "ខុស", "Check if any answer is wrong.", "ពិនិត្យមើលថាតើមានចម្លើយណាមួយខុសឬទេ។"),
            ("wrap", "/ræp/", "verb", "🎁", "cover or enclose in paper or soft material", "ខ្ចប់", "Wrap the birthday gift in colorful paper.", "ខ្ចប់កាដូថ្ងៃកំណើតក្នុងក្រដាសពណ៌ឆើតឆាយ។"),
            ("wreck", "/rek/", "noun", "🚢", "the destruction of a ship or vehicle", "ការខូចខាត/បាក់បែក", "Divers explored the ancient shipwreck.", "អ្នកមុជទឹកបានរុករកនាវាបាក់បែកបុរាណ។"),
            ("wren", "/ren/", "noun", "🐦", "a small short-winged songbird", "ចាបតូច", "A tiny wren nested in the thick hedge.", "ចាបតូចមួយធ្វើសំបុកនៅក្នុងរបងព្រៃក្រាស់។"),
            ("wring", "/rɪŋ/", "verb", "🧼", "squeeze and twist to extract liquid", "ពូត", "Wring out the wet cloth before drying.", "ពូតកំណាត់សើមមុនពេលសម្ងួត។"),
            ("climb", "/klaɪm/", "verb", "🧗", "go up or ascend using hands and feet", "ឡើង", "We want to climb the high mountain.", "ពួកយើងចង់ឡើងភ្នំដ៏ខ្ពស់។"),
            ("lamb", "/læm/", "noun", "🐑", "a young sheep", "កូនចៀម", "The small white lamb followed its mother.", "កូនចៀមពណ៌សតូចបានដើរតាមម្តាយរបស់វា។"),
            ("comb", "/koʊm/", "noun", "🪮", "strip of plastic with teeth for untangling hair", "ស្និត", "Use a comb to tidy your hair.", "ប្រើស្និតដើម្បីសិតសក់របស់អ្នកឱ្យមានរបៀប។"),
            ("bomb", "/bɒm/", "noun", "💣", "explosive weapon detonated by fuse or impact", "គ្រាប់បែក", "The museum displayed a historic bomb.", "សារមន្ទីរបានដាក់បង្ហាញគ្រាប់បែកប្រវត្តិសាស្ត្រមួយ។"),
            ("thumb", "/θʌm/", "noun", "👍", "short thick first digit of the human hand", "មេដៃ", "He cut his thumb cutting vegetables.", "គាត់បានមុតមេដៃពេលកាត់បន្លែ។"),
            ("debt", "/det/", "noun", "💸", "money owed that is due for payment", "បំណុល", "He paid off his financial debt.", "គាត់បានសងបំណុលហិរញ្ញវត្ថុរបស់គាត់រួចរាល់។"),
            ("doubt", "/daʊt/", "noun", "❓", "feeling of uncertainty or lack of conviction", "ការសង្ស័យ", "There is no doubt that she will pass.", "គ្មានការសង្ស័យទេថានាងនឹងប្រឡងជាប់។"),
            ("limb", "/lɪm/", "noun", "🌳", "arm or leg of a person; large branch of a tree", "មែកធាង/សរីរាង្គ", "The monkey swung from a tree limb.", "ស្វាកំពុងលោតពីមែកធាងឈើមួយទៅមែកមួយទៀត។"),
            ("dumb", "/dʌm/", "adjective", "🤫", "unable to speak; temporarily silent or stupid", "គ", "He stood dumb with astonishment.", "គាត់បានឈរគដោយការភ្ញាក់ផ្អើល។"),
            ("numb", "/nʌm/", "adjective", "🥶", "deprived of physical sensation or feel", "ស្ពឹក", "My fingers were numb in the cold snow.", "ម្រាមដៃរបស់ខ្ញុំបានស្ពឹកនៅក្នុងទឹកកកត្រជាក់។"),
            ("sign", "/saɪn/", "noun", "🪧", "gesture or object that conveys information", "ស្លាកសញ្ញា", "Look at the stop sign on the corner.", "មើលស្លាកសញ្ញាឈប់នៅជ្រុងផ្លូវ។"),
            ("gnat", "/næt/", "noun", "🪰", "small two-winged biting fly insect", "មូសតូច/រុយតូច", "A tiny gnat buzzed around my ear.", "មូសតូចមួយបានហើរលាន់ឮជុំវិញត្រចៀករបស់ខ្ញុំ។"),
            ("gnaw", "/nɔː/", "verb", "🦷", "bite or chew on something persistently", "កកេរ", "Rats like to gnaw on wood blocks.", "កណ្តុរចូលចិត្តកកេរលើដុំឈើ។"),
            ("gnome", "/noʊm/", "noun", "🧙", "small legendary dwarf in folklore guarding earth", "មនុស្សតឿព្រៃ", "They put a garden gnome on the lawn.", "ពួកគេបានដាក់រូបមនុស្សតឿព្រៃនៅលើវាលស្មៅ។"),
            ("ghost", "/ɡoʊst/", "noun", "👻", "apparition of a dead person", "ខ្មោច", "He dressed up as a white ghost for Halloween.", "គាត់បានតែងខ្លួនជាខ្មោចពណ៌សសម្រាប់បុណ្យ Halloween។"),
            ("honest", "/ˈɒnɪst/", "adjective", "😇", "free of deceit; truthful and sincere", "ស្មោះត្រង់", "Give an honest answer to the teacher.", "ផ្តល់ចម្លើយដ៏ស្មោះត្រង់ទៅកាន់គ្រូ។"),
            ("hour", "/ˈaʊər/", "noun", "⌛", "period of time equal to sixty minutes", "ម៉ោង", "We practiced English for an hour.", "ពួកយើងបានអនុវត្តភាសាអង់គ្លេសរយៈពេលមួយម៉ោង។"),
            ("honor", "/ˈɒnər/", "noun", "🎖️", "high respect or great privilege", "កិត្តិយស", "It is an honor to win this medal.", "វាជាកិត្តិយសណាស់ដែលបានឈ្នះមេដាយនេះ។"),
            ("heir", "/eər/", "noun", "👑", "person inheriting property or rank", "អ្នកស្នងមរតក", "The prince is the heir to the throne.", "ព្រះអង្គម្ចាស់គឺជាអ្នកស្នងមរតករាជបល្ល័ង្ក។"),
            ("listen", "/ˈlɪsən/", "verb", "👂", "give attention to sound or hear", "ស្តាប់", "Listen to the pronunciation carefully.", "ស្តាប់ការបញ្ចេញសំឡេងឱ្យបានច្បាស់។"),
            ("castle", "/ˈkɑːsəl/", "noun", "🏰", "large fortified stone building of royalty", "ប្រាសាទ/បន្ទាយ", "The ancient castle sits on the rocky hill.", "ប្រាសាទបុរាណស្ថិតនៅលើកូនភ្នំថ្ម។"),
            ("whistle", "/ˈwɪsəl/", "noun", "🪈", "clear high-pitched sound made by blowing; tool", "កញ្ចែ/ whistling", "The referee blew his silver whistle.", "អាជ្ញាកណ្តាលបានផ្លុំកញ្ចែប្រាក់របស់គាត់។"),
            ("hustle", "/ˈhʌsəl/", "verb", "🏃", "busy activity; push roughly; hurry", "ប្រញាប់ប្រញាល់/ប្រឹងប្រែង", "We had to hustle to catch the school bus.", "ពួកយើងត្រូវតែប្រញាប់ប្រញាល់ដើម្បីទាន់ឡានសាលា។"),
            ("rustle", "/ˈrʌsəl/", "noun", "🍂", "soft crackling sound of dry leaves", "សំឡេងខ្សកខ្សាក", "We heard a rustle of leaves in the forest.", "ពួកយើងបានឮសំឡេងខ្សកខ្សាកនៃស្លឹកឈើនៅក្នុងព្រៃ។"),
            ("fasten", "/ˈfɑːsən/", "verb", "🔒", "close or join securely", "រឹតបន្តឹង/ចងភ្ជាប់", "Fasten your seat belt before driving.", "រឹតបន្តឹងខ្សែក្រវ៉ាត់សុវត្ថិភាពរបស់អ្នកមុនពេលបើកបរ។"),
            ("soften", "/ˈsɒfən/", "verb", "🧴", "make or become less hard or softer", "ធ្វើឱ្យទន់", "Use warm water to soften the clay.", "ប្រើទឹកក្តៅឧណ្ហៗដើម្បីធ្វើឱ្យដីឥដ្ឋទន់។"),
            ("match", "/mætʃ/", "noun", "🏏", "contest in game; stick for lighting fire", "ការប្រកួត/ឈើគូស", "We watched an exciting football match.", "ពួកយើងបានមើលការប្រកួតបាល់ទាត់ដ៏រំភើបមួយ។"),
            ("watch", "/wɒtʃ/", "verb", "⌚", "look at attentively; small timepiece on wrist", "មើល/នាឡិកាដៃ", "Watch the screen; check your wrist watch.", "មើលអេក្រង់; ពិនិត្យមើលនាឡិកាដៃរបស់អ្នក។"),
            ("catch", "/kætʃ/", "verb", "🫴", "intercept and hold a falling object", "ចាប់", "Try to catch the ball in the air.", "ព្យាយាមចាប់បាល់នៅលើអាកាស។"),
            ("pitch", "/pɪtʃ/", "noun", "⚽", "field of play in sport; quality of high/low sound", "ទីលាន/កម្រិតសំឡេង", "The football match is played on a green pitch.", "ការប្រកួតបាល់ទាត់ត្រូវបានលេងនៅលើទីលានពណ៌បៃតង។"),
            ("patch", "/pætʃ/", "noun", "🩹", "piece of cloth used to cover a hole", "បំណះ", "My mom sewed a patch on my jeans.", "ម្តាយរបស់ខ្ញុំបានដេរបំណះនៅលើខោខូវប៊យរបស់ខ្ញុំ។"),
            ("knife", "/naɪf/", "noun", "🔪", "a tool with a blade for cutting", "កាំបិត", "We cut the cake with a knife.", "ពួកយើងកាត់នំខេកដោយប្រើកាំបិត។"),
            ("knit", "/nɪt/", "verb", "🧶", "to loop yarn to make fabric", "ត្បាញ", "She learned how to knit a scarf.", "នាងបានរៀនពីរបៀបត្បាញកន្សែងបង់ក។")
        ]
    },
    # CATEGORY 8: Double Consonants (50 words)
    {
        "category": "Double Consonants",
        "words": [
            ("bell", "/bel/", "noun", "🔔", "hollow metal object that rings when struck", "ជួង/កណ្តឹង", "The school bell rang at noon.", "ជួងសាលាបានរោទ៍នៅថ្ងៃត្រង់។"),
            ("cell", "/sel/", "noun", "🧫", "smallest structural unit of an organism", "កោសិកា/បន្ទប់តូច", "A plant cell is green under the microscope.", "កោសិការុក្ខជាតិមានពណ៌បៃតងនៅក្រោមមីក្រូទស្សន៍។"),
            ("doll", "/dɒl/", "noun", "🪆", "small model of a human being as a toy", "តុក្កតា", "The little girl played with a doll.", "ក្មេងស្រីតូចបានលេងជាមួយតុក្កតា។"),
            ("fall", "/fɔːl/", "verb", "🍂", "drop downwards of weight under gravity", "ធ្លាក់", "Dry leaves fall from trees in autumn.", "ស្លឹកឈើស្ងួតធ្លាក់ពីលើដើមឈើនៅរដូវស្លឹកឈើជ្រុះ។"),
            ("hill", "/hɪl/", "noun", "⛰️", "naturally raised area of land smaller than mountain", "កូនភ្នំ", "We ran up the grassy green hill.", "ពួកយើងបានរត់ឡើងលើកូនភ្នំស្មៅពណ៌បៃតង។"),
            ("mill", "/mɪl/", "noun", "🏭", "building fitted with machinery for grinding grain", "ម៉ាស៊ីនកិនស្រូវ", "Wheat is turned into flour at the mill.", "ស្រូវសាលីត្រូវបានកិនទៅជាម្សៅនៅឯម៉ាស៊ីនកិនស្រូវ។"),
            ("pill", "/pɪl/", "noun", "💊", "small round mass of solid medicine to swallow", "ថ្នាំគ្រាប់", "He swallowed the medicine pill with water.", "គាត់បានលេបថ្នាំគ្រាប់ជាមួយទឹក។"),
            ("tall", "/tɔːl/", "adjective", "🦒", "of great stature or height", "ខ្ពស់", "Giraffes are the tallest land animals.", "សត្វក giraffe គឺជាសត្វដីគោកដែលខ្ពស់ជាងគេ។"),
            ("wall", "/wɔːl/", "noun", "🧱", "continuous upright brick structure defining area", "ជញ្ជាំង", "A family photo hung on the wall.", "រូបថតគ្រួសារបានព្យួរនៅលើជញ្ជាំង។"),
            ("yell", "/jel/", "verb", "🗣️", "give a loud, sharp cry; shout", "ស្រែក", "Don't yell, speak quietly.", "កុំស្រែក និយាយតិចៗ។"),
            ("class", "/klæs/", "noun", "🏫", "course of instruction or classroom group", "ថ្នាក់", "She was elected leader of the class.", "នាងត្រូវបានគេបោះឆ្នោតឱ្យធ្វើជាប្រធានថ្នាក់។"),
            ("glass", "/ɡlæs/", "noun", "🥛", "hard transparent material for windows/cups", "កែវ/កញ្ចក់", "Be careful, the glass is hot.", "ប្រយ័ត្ន កែវពិតជាក្តៅណាស់។"),
            ("grass", "/ɡræs/", "noun", "🌱", "common wild green lawn plant", "ស្មៅ", "The green grass grew tall in the rain.", "ស្មៅពណ៌បៃតងបានដុះខ្ពស់ក្នុងពេលភ្លៀង។"),
            ("pass", "/pæs/", "verb", "🎫", "go past or bypass; succeed in test", "ឆ្លងកាត់/ជាប់", "He worked hard to pass the English test.", "គាត់បានប្រឹងប្រែងធ្វើការដើម្បីប្រឡងជាប់ភាសាអង់គ្លេស។"),
            ("boss", "/bɒs/", "noun", "👔", "person in charge of worker employees", "មេ/ប្រធាន", "The boss scheduled a staff meeting.", "ប្រធានបានរៀបចំកិច្ចប្រជុំបុគ្គលិក។"),
            ("kiss", "/kɪs/", "verb", "😘", "touch with lips as a sign of affection", "ថើប", "She gave her sister a gentle kiss.", "នាងបានថើបប្អូនស្រីរបស់នាងថ្នមៗ។"),
            ("miss", "/mɪs/", "verb", "😢", "fail to hit or catch; feel regret about absence of", "នឹក/ខកខាន", "I miss my grandparents very much.", "ខ្ញុំនឹកជីដូនជីតារបស់ខ្ញុំខ្លាំងណាស់។"),
            ("less", "/les/", "adjective", "➖", "a smaller amount or quantity", "តិចជាង", "Spend less time playing and more studying.", "ចំណាយពេលលេងឱ្យតិច ហើយរៀនឱ្យបានច្រើន។"),
            ("mess", "/mes/", "noun", "🧹", "dirty or untidy state of things", "ភាពរញ៉េរញ៉ៃ", "Clean up the mess on the floor.", "សម្អាតភាពរញ៉េរញ៉ៃនៅលើឥដ្ឋ។"),
            ("puff", "/pʌf/", "noun", "💨", "short explosive emission of wind or smoke", "ផ្សែងហុយ/ខ្យល់បក់", "A puff of white smoke rose from the chimney.", "ផ្សែងហុយពណ៌សមួយបានហុយឡើងពីបំពង់ផ្សែង។"),
            ("cuff", "/kʌf/", "noun", "👕", "end part of a sleeve, where the hand emerges", "កដៃអាវ", "Fasten the button on your shirt cuff.", "រឹតប៊ូតុងនៅលើកដៃអាវរបស់អ្នក។"),
            ("huff", "/hʌf/", "verb", "😤", "blow out loudly; get annoyed easily", "ដកដង្ហើមធំដោយធុញទ្រាន់", "He walked up the hill with a huff.", "គាត់បានដើរឡើងលើកូនភ្នំដោយដកដង្ហើមធំ។"),
            ("stiff", "/stɪf/", "adjective", "🧍", "rigid or firm; not easily bent", "រឹង/ស្ពឹក", "My muscles felt stiff after the run.", "សាច់ដុំរបស់ខ្ញុំមានអារម្មណ៍ថារឹងបន្ទាប់ពីរត់រួច។"),
            ("cliff", "/klɪf/", "noun", "⛰️", "steep high face of rock", "ច្រាំងថ្មចោទ", "The ancient lighthouse stands on a high cliff.", "បង្គោលភ្លើងបុរាណស្ថិតនៅលើច្រាំងថ្មចោទដ៏ខ្ពស់។"),
            ("buzz", "/bʌz/", "verb", "🐝", "humming sound made by flying insects", "ញ័រ/លាន់ឮ", "We heard the bees buzz in the garden.", "ពួកយើងបានឮសត្វឃ្មុំលាន់ឮនៅក្នុងសួនច្បារ។"),
            ("fizz", "/fɪz/", "verb", "🫧", "make a hissing bubbly sound", "ពពុះហុយ/ឮសំឡេងពពុះ", "The soda began to fizz when opened.", "សូដាបានចាប់ផ្តើមពុះនៅពេលបើក។"),
            ("fuzz", "/fʌz/", "noun", "🍑", "fluffy mass of fibers or hair", "រោមទន់ៗ", "Peaches are covered in fine soft fuzz.", "ផ្លែប៉េសត្រូវបានគ្របដណ្តប់ដោយរោមទន់ៗ។"),
            ("jazz", "/dʒæz/", "noun", "🎷", "type of music of African-American origin", "តន្ត្រីហ្សាស", "He plays the saxophone in a jazz band.", "គាត់លេងសាក់សូហ្វូននៅក្នុងក្រុមតន្ត្រីហ្សាស។"),
            ("add", "/æd/", "verb", "➕", "join one thing to another to increase size", "បូក/បន្ថែម", "Add two numbers together in math.", "បូកលេខពីរបញ្ចូលគ្នានៅក្នុងគណិតវិទ្យា។"),
            ("odd", "/ɒd/", "adjective", "❓", "strange or unusual; not even numbers", "ចម្លែក/លេខសេស", "Three is an odd number.", "លេខបីគឺជាលេខសេស។"),
            ("mud", "/mʌd/", "noun", "🟫", "wet soft earthy material", "ភក់", "The dog covered its paws in brown mud.", "ឆ្កែបានប្រឡាក់ជើងរបស់វានៅក្នុងភក់ពណ៌ត្នោត។"),
            ("saddle", "/ˈsædəl/", "noun", "🏇", "leather seat fastened on back of a horse", "កែបសេះ", "He buckled the leather saddle tightly.", "គាត់បានចងកែបសេះស្បែកយ៉ាងណែន។"),
            ("puddle", "/ˈpʌdəl/", "noun", "💦", "small pool of liquid, typically rainwater", "ថ្លុកទឹក", "The kid jumped into a rainwater puddle.", "ក្មេងបានលោតចូលទៅក្នុងថ្លុកទឹកភ្លៀង។"),
            ("middle", "/ˈmɪdəl/", "noun", "📍", "the point or position equidistant from ends", "កណ្តាល", "The yellow house is in the middle of the street.", "ផ្ទះពណ៌លឿងស្ថិតនៅកណ្តាលផ្លូវ។"),
            ("butter", "/ˈbʌtər/", "noun", "🧈", "pale yellow fatty substance made of milk", "ប៊ឺ", "Spread some soft butter on the bread.", "លាបប៊ឺទន់ៗនៅលើនំប៉័ង។"),
            ("letter", "/ˈletər/", "noun", "✉️", "written message in envelope; alphabet symbol", "សំបុត្រ/អក្សរ", "She sent a letter to her friend.", "នាងបានផ្ញើសំបុត្រទៅមិត្តភក្តិរបស់នាង។"),
            ("bottle", "/ˈbɒtəl/", "noun", "🍼", "glass or plastic container with a narrow neck", "ដប", "Fill the bottle with clean drinking water.", "បំពេញដបដោយទឹកផឹកស្អាត។"),
            ("kitten", "/ˈkɪtən/", "noun", "🐱", "a young cat", "កូនឆ្មា", "The play kitten chased the ball of yarn.", "កូនឆ្មាកំពុងដេញតាមដុំរោមចៀម។"),
            ("bitter", "/ˈbɪtər/", "adjective", "☕", "having a sharp, pungent taste; not sweet", "ល្វីង", "Dark coffee has a bitter taste.", "កាហ្វេខ្មៅមានរសជាតិល្វីង។"),
            ("little", "/ˈlɪtəl/", "adjective", "🐭", "small in size, amount, or degree", "តូច", "A little mouse crawled in the room.", "កណ្តុរតូចមួយបានវារចូលក្នុងបន្ទប់។"),
            ("apple", "/ˈæpəl/", "noun", "🍎", "round fruit with red or green skin", "ផ្លែប៉ោម", "Eat a sweet red apple daily.", "ញ៉ាំផ្លែប៉ោមពណ៌ក្រហមផ្អែមរៀងរាល់ថ្ងៃ។"),
            ("happy", "/ˈhæpi/", "adjective", "😊", "feeling or showing pleasure or contentment", "រីករាយ/សប្បាយចិត្ត", "They had a happy party together.", "ពួកគេមានពិធីជប់លៀងដ៏រីករាយជាមួយគ្នា។"),
            ("puppy", "/ˈpʌpi/", "noun", "🐶", "a young dog", "កូនឆ្កែ", "The playful puppy wagged its tail.", "កូនឆ្កែដ៏គួរឱ្យស្រឡាញ់បានគ្រវីកន្ទុយរបស់វា។"),
            ("copper", "/ˈkɒpər/", "noun", "🪙", "red-brown metal; chemical element", "ទង់ដែង", "The old wires were made of copper.", "ខ្សែភ្លើងចាស់ៗធ្វើពីទង់ដែង។"),
            ("hammer", "/ˈhæmər/", "noun", "🔨", "tool with a heavy metal head used for hitting nails", "ញញួរ", "Use a hammer to drive the nail in.", "ប្រើញញួរដើម្បីវាយដែកគោលចូល។"),
            ("summer", "/ˈsʌmər/", "noun", "☀️", "the warmest season of the year", "រដូវក្តៅ", "We go swimming in the hot summer.", "ពួកយើងទៅហែលទឹកនៅរដូវក្តៅដ៏ក្តៅ។"),
            ("drummer", "/ˈdrʌmər/", "noun", "🥁", "person who plays the drums in a band", "អ្នកវាយស្គរ", "The drummer kept a fast beat for the song.", "អ្នកវាយស្គរបានរក្សាជន្នះយ៉ាងលឿនសម្រាប់ចម្រៀង។"),
            ("dimmer", "/ˈdɪmər/", "noun", "💡", "device for varying brightness of light", "ឧបករណ៍សម្រួលពន្លឺ", "Turn the dimmer to lower the light.", "បង្វិលឧបករណ៍សម្រួលពន្លឺដើម្បីបន្ថយពន្លឺ។"),
            ("common", "/ˈkɒmən/", "adjective", "👥", "occurring, found, or done often; shared", "ទូទៅ/រួម", "Pigeons are a common bird in cities.", "ព្រាបគឺជាសត្វស្លាបទូទៅនៅក្នុងទីក្រុង។"),
            ("bottom", "/ˈbɒtəm/", "noun", "🍑", "the lowest point or part of something", "ផ្នែកខាងក្រោម", "The keys fell to the bottom of the bag.", "សោបានធ្លាក់ទៅបាតកាបូប។")
        ]
    }
]

# Generate JSON entries
id_counter = 1
for cat_data in raw_data:
    category = cat_data["category"]
    for item in cat_data["words"]:
        word, ipa, word_type, emoji, definition, definition_kh, example, example_kh = item
        phonics_words.append({
            "id": id_counter,
            "word": word,
            "ipa": ipa,
            "type": word_type,
            "emoji": emoji,
            "definition": definition,
            "definitionKh": definition_kh,
            "example": example,
            "exampleKh": example_kh,
            "category": category
        })
        id_counter += 1

print(f"Generated {len(phonics_words)} phonics words.")

# Ensure directory exists and write JSON
os.makedirs("/Users/chrisj0923/Development/EnglishEducation/src/data", exist_ok=True)
output_path = "/Users/chrisj0923/Development/EnglishEducation/src/data/phonics_words.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(phonics_words, f, ensure_ascii=False, indent=2)

print(f"Successfully saved phonics words to {output_path}")
